### ISSUE TITLE
Rename flask-restplus -> flask-restx

### ISSUE THREAD

**Issue by SteadBytes** [python-restx/flask-restx#1]
All occurrences of Flask-RESTPlus, flask-restplus e.t.c. should be replaced with Flaks-RESTX, flask-restx e.t.c. In addition, the Flask-RESTPlus logo should also be removed until a Flask-RESTX logo is created.

**Comment by SteadBytes** [comment]
I think this can be closed now, unless anyone can spot any that I've missed! :smile:

**Comment by ziirish** [comment]
Seems good to me now.
I spotted the configuration variables while working on the logo, I thought this was expected at first.

**Comment by SteadBytes** [comment]
No worries @ziirish ! Thanks for taking a look :smile:
