### ISSUE TITLE
is it a drop-in replacement for flask-restplus?

### ISSUE THREAD

**Issue by andreixk** [python-restx/flask-restx#10]
I've been using flask-restplus for a while now, just wondering if i simply rename imports, will everything else work with current syntax?

edit: not sure how to remove the BUG label

**Comment by ziirish** [comment]
Yes, that's the idea for now.Just replace all your imports, we also renamed the configuration keys. That's it.Note: there is a package already on Pypi but it doesn't reflect any recent change so please don't use it yet. I just pushed a dummy package to reserve the name. We are at the early stages of the fork and we still have a few things to be discussed/done.We'll let you know when things are ready.

**Comment by ziirish** [comment]
Our very first release is now available.

I'll update the docs with the migration process to replace `flask-restplus` with `flask-restx`.

**Comment by amickael** [comment]
Thank you for everything you guys do, this is one of my favorite libraries in the Python ecosystem.
