### ISSUE TITLE
Integrate marshmallow

### ISSUE THREAD

**Issue by mcclurem** [python-restx/flask-restx#11]
There exists a huge pile of forks etc of the flask_restful family and the one thing that seems to be missing consistently is native support for marshmallow. It would be really great if restx finally integrated that.
The flask-restplus-patched project exists but its based off ancient apispec and so it's not quite there

**Comment by SteadBytes** [comment]
Hi @mcclurem this is something we will be potentially addressing soon. For the moment, we're just getting things sorted out on this new fork and then we will be planning our roadmap of feature development. Models and serialisation in general is definitely high on the list of priorities and this *may* include Marshmallow. 

Keep an eye out for developments coming soon and do head on over to the Gitter channel if you would like further discussion :smile:

**Comment by anandtripathi5** [comment]
@SteadBytes I am curiously waiting for the support of webargs and marshmallow in flask-restx. Is there any progress happening on that side?
