### ISSUE TITLE
Add support for recursive nested models

### ISSUE THREAD

**Issue by louise-davies** [python-restx/flask-restx#110]
**Is your feature request related to a problem? Please describe.**
Currently, `flask-restx` swagger.json generation breaks when one defines some models with recursive/circular references to one another. See noirbizarre/flask-restplus#190

**Describe the solution you'd like**
A PR was made in the `flask-resplus` repo that fixes the issue: noirbizarre/flask-restplus#656

**Comment by dgrine** [comment]
Has there been any progress on this?
