### ISSUE TITLE
Improve configuration docs

### ISSUE THREAD

**Issue by SteadBytes** [python-restx/flask-restx#123]
In response to a recent issue, I've started a dedicated documentation page for the configuration options supported by Flask-RESTX https://github.com/python-restx/flask-restx/commit/990bd355e17d6c7111e745df8763da80265cd50d . Most of these are documented *somewhere*, however it would be beneficial for users if these were detailed in this single page
- The page currently *lists* all of them without further details.

**Comment by ziirish** [comment]
I actually started this work in #112

**Comment by SteadBytes** [comment]
Oh excellent - thank you for starting that! Apologies for not noticing the open PR (looking good btw). How would you like to proceed? Shall we extract the configuration section from your PR and use it to address this issue?

**Comment by ziirish** [comment]
Whatever best fits for you.

**Comment by SteadBytes** [comment]
Ok, so I think we should remove the configuration section from https://github.com/python-restx/flask-restx/pull/112 and merge it as its been open a while now (again, apologies). Then create a new PR to edit `doc/configuration.rst` with the extra detail that was removed. Does that sound ok?

**Comment by ziirish** [comment]
Yes, sure. I'll try to do it tonight.

**Comment by SteadBytes** [comment]
Awesome thanks. Let me know if you'd like any help moving things around (it's my fault that we need to do so anyway) and/or any review needed 👍

**Comment by ziirish** [comment]
I have opened #125 and updated #112.

**Comment by SteadBytes** [comment]
Awesome! #125 is merged :+1: I'll leave this issue open for now as there's still more to be done here but this a great start :smile:

**Comment by SteadBytes** [comment]
There's always room for documentation improvement but I'm closing this now #125 and #112 are merged - thanks @ziirish  :smile:
