### ISSUE TITLE
Contributing getting started questions

### ISSUE THREAD

**Issue by ramarivera** [python-restx/flask-restx#124]
Hi everyone!

I've been following this project back when it was still flask-restplus, and I've always wanted to contribute back to it since I've used it and liked it quite a bit. 

So I wanted to know two things since now I find myself with some time for contributing:

1. Do you have an specific messaging channel, like discord, slack, gitter, etc? 
2. Do you already have in mind a list of issues that are a good "first contribution" candidate?

Thanks in advanced!

**Comment by j5awry** [comment]
1. Yes, we have a gitter channel! https://gitter.im/python-restx/community

2. We been using labels, but don't have a "good first task" type label. There are a number of documentation related issues though! We definitely need help cleaning up the documentation. 

Engaging on gitter is the best way to catch more of our attention

**Comment by ramarivera** [comment]
Awesome then! I’ll join the glitter and just close this issue then
