### ISSUE TITLE
Add support to config swagger-ui using app.config

### ISSUE THREAD

**Issue by tjysdsg** [python-restx/flask-restx#13]
I came across a problem that probably can only be solved by asking you maintainers of this package. 

My need: Show `model` tab by default, instead of `example value`, in the `parameters` section in API method documentation.

![image](https://user-images.githubusercontent.com/21212505/72528996-5087ea80-38a7-11ea-80d6-5ebabee89b62.png)

The method that I tried: According [docs for `Swagger-UI` configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#configuration), I can set `DEFAULT_MODEL_RENDERING` to `"model"` to make this happen.

Why didn't work: Since `flask-restplus` doesn't seems to do anything when I set `app.config.SWAGGER_UI_DEFAULT_MODEL_RENDERING` to `"model"`, I suppose allowing users to set custom configurations of `Swagger-UI` could be a feature added to `flask-restx`.

**Comment by SteadBytes** [comment]
Hi @tjysdsg, unfortunately there is currently not support for all of the available Swagger UI configuration options - only those mentioned in the documentation. We are currently getting the project initial setup work sorted out after creating this fork but soon we will be planning our feature development roadmap. This (or something similar) is a good idea so thank you! 

In the meantime, if you require this change urgently, you could set a custom Flask template for the Swagger UI. Here's the file used in `flask-restx` https://github.com/python-restx/flask-restx/blob/master/flask_restx/templates/swagger-ui.html#L50 . If you copy the contents of that to `templates/swagger-ui.html` in your project it will take precedence over the one shipped with `flask-restx`. You can then change the configuration parameters for Swagger UI in that template. Hopefully it will be only a temporary solution as we will be able to provide better support for this configuration with `flask-restx` directly. Here's how it would look in the `flask-restplus/examples` directory:

```
.
├── complex.py
├── templates
│   └── swagger-ui.html    <-------- Here's the new template!
├── todo_blueprint.py
├── todomvc.py
├── todo.py
├── todo_simple.py
├── xml_representation.py
└── zoo
    ├── cat.py
    ├── dog.py
    ├── __init__.py
```

**Comment by tjysdsg** [comment]
Oh thank you, the temporary solution is good for me right now. However, I have opened a pull request #14, and could you please check it out? Thanks in advance.

**Comment by SteadBytes** [comment]
Great, glad to help. I have replied to you PR and closed it for now - please read my response! 😊 I've captured the general problem in a new issue and it will be addressed in due course! Keep an eye out and please feel free to head on over to Gitter to discuss 😊
