### ISSUE TITLE
Can't access swagger.json through https + docker proxyfied

### ISSUE THREAD

**Issue by jaesivsm** [python-restx/flask-restx#133]
I'm not sure this is a bug or the way to fix it but here is how things happen :

### **Repro Steps** 
I'm serving a `flask-restx` app on a docker behind a reverse proxy. 
The proxy serves HTTPS and proxies the requests to the docker in HTTP.

### **Expected Behavior**
I'd want the UI, accessed through HTTPS => HTTP to be able to reach the `swagger.json`.

### **Actual Behavior**
If I try to access to swagger documentation, it fails to load the `swagger.json`. The UI notes that it tries to access the Json file via HTTP. 
After some digging I understood that's because the `swagger.json` URL is constructed through `url_for` which, in the context of a request, uses the scheme of said request. The request being the one between the proxy and the docker, the scheme is HTTP.
Even if I configure flask with `PREFERED_URL_SCHEME` the fact that the `url_for` is executed in the context of a request will override the configured preference.
It is to be noted that the HTTP URL of the `swagger.json` does redirect to a valid HTTPS one. But the swagger bundle doesn't seem to try to follow redirection.

### Bugfixes idea : 
I'm not sure if it's really a bug but here's what I could implement : 
 * building the URL at load time, outside any context. I think it would fix my bug but I'm not sure it is wanted or wouldn't have undesired side effects (I am not very familiar with the depths of `flask-restx`)
 * I didn't find how to make swagger js bundle follow redirection to the HTTPS resource but there must be something to dig there.

### **Environment**
- Python version 3.7
- Flask version 1.0.2
- Flask-RESTX version 0.1.1

**Comment by j5awry** [comment]
have you looked at Werkzeug proxy_fix? this can be used to solve many reverse proxy issues:

https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/

**Comment by jaesivsm** [comment]
@j5awry Great solution, thanks a lot ! With the right headers from the proxy worked like a charm. Thanks again !

**Comment by zooyf** [comment]
Hey, I encountered with the same problem.
How did you solve the problem? Could you please show your code here?
Thanks a lot

> @j5awry Great solution, thanks a lot ! With the right headers from the proxy worked like a charm. Thanks again !

**Comment by jaesivsm** [comment]
Ok so basically here the werkzeug Proxy in my project [wsgi.py](https://github.com/jaesivsm/JARR/blob/bdd5d85238f978597b916d4544255e07e22f6900/wsgi.py#L6) 
And here is a shortened version of my apache conf : 
```apache
<VirtualHost *:443>
    ServerName api.jarr.info
    SetOutputFilter DEFLATE
    ProxyPass / http://127.0.0.1:8500/
    ProxyPassReverse / http://127.0.0.1:8500/
    RequestHeader set X-Forwarded-Proto https
</VirtualHost>       
```
