### ISSUE TITLE
Question about Pagination

### ISSUE THREAD

**Issue by cedricbonhomme** [python-restx/flask-restx#138]
**Ask a question**
Hello,

Could someone please advise me on how to do pagination, let say the _proper way_?

Nothing is mentioned in the documentation and https://github.com/mtShaikh/flask-rest-paginate seems not very used (has been designed for Flask-restful).

Is the better solution to do everything by hand?

thank you very much!

**Comment by cedricbonhomme** [comment]
not urgent, since it is quite easy to manage this manually.

But I will be always interested if there is a recommended way

**Comment by mafeko** [comment]
Hi @cedricbonhomme.
I went along the [video](https://youtu.be/OTWs0wPHU-g?t=800) from flask-restplus (project forked from) and implemented pagination like this:

```python
pagination_parser = RequestParser()
pagination_parser.add_argument(
    "pageNumber", type=int, required=False, default=1, help="Page number"
)
pagination_parser.add_argument(
    "pageSize", type=int, required=False, default=10, help="Page size"
)


@api.route("/")
class PaginationExample(Resource):
    @api.expect(pagination_parser)
    def get(self):
        p_args = pagination_parser.parse_args()
        
        p_args.get("pageNumber")
        p_args.get("pageSize")
        # ... your code
        pass
```

Hope this helps.

**Comment by cedricbonhomme** [comment]
Thank you for the tip! Using a dedicated RequestParser is a good idea.
