### ISSUE TITLE
Future of Restx

### ISSUE THREAD

**Issue by min2bro** [python-restx/flask-restx#144]
**Ask a question**
I'm coming from the background of Flask Restplus and we have developed web apps and rest api's which were fully functional and working in production but the things gone really awry when we updated Werkzeug==1.0.0 and thereafter we learnt that flask restplus is dead ([Issue#770](https://github.com/noirbizarre/flask-restplus/issues/770))

We are planning to upgrade the flask restplus to restx but wanted to check with the Maintainer and Core-developers how reliable it will be to go with the Restx from a future perspective. Since we don't want to get into the same situation as Flask restplus So wanted to confirm if Restx can be trusted for production update and if there will be a support in a long run and will not met the fate of restplus.

**Comment by ziirish** [comment]
Hi,

Unlike Flask-RESTPlus which was a one-man handled project, Flask-RESTX is a community driven project.
We put in place automation to ease release publication (the main reason we had to fork is that none of the maintainers had permissions on the PyPi project).

Unfortunately, the current maintainers (including myself) have not been very active on the project since the beginning of the COVID situation.
But we'll be happy to welcome any contribution/contributors.

**Comment by min2bro** [comment]
Hi @ziirish 

Thanks for the info. what I understand is flask restx is a fork of restplus. So how frequently the bugs and feature request are implemented? Is there any release schedule in place for rest-x?

**Comment by j5awry** [comment]
There is no set release schedule for flask-restx (nor was there one for restplus). We normally decide a release by chatting in a "maintainers" gitter channel. We take bugfixes from the community somewhat regularly. I'd say a couple of us focus on just "release manager" type tasks in that regard -- we check PRs, give approvals, make sure tests are passing and branches are up to date, etc. We rely heavily on the community.

 We're a small group where a number of us have transitioned away from web development, but still want to make sure this stays alive. I'm one of those folks (I haven't done any web-dev in 6+ months, maybe close to a year at this point).

We're totally on board with more people joining in. The more active contributors, and the more contributors that are actively _using_ flask-restx, the better.

**Comment by min2bro** [comment]
Thanks @j5awry and @ziirish . I think you guys have given me enough food for thought to make a decision whether to build a production level REST API using Flask-RESTX or not. Appreciate that. Thanks once again.
