### ISSUE TITLE
Rate Limit Implementation

### ISSUE THREAD

**Issue by Aletz-Arce** [python-restx/flask-restx#145]
**AHow to implement API rate limit?**
Hi, anyone already implement rate limit feature, you can me advise ?
Flask-Limiter its the best way?
Thanks

**Comment by onlinejudge95** [comment]
As far as I think, the task of `Flask-RESTX` is to provide a REST Framework for `flask` compatible with `swagger`. I don't see why RATE limiting would fall in this bucket. Personally I think rate-limiting should be implemented outside `Flask-RESTX`

**Comment by Aletz-Arce** [comment]
> As far as I think, the task of `Flask-RESTX` is to provide a REST Framework for `flask` compatible with `swagger`. I don't see why RATE limiting would fall in this bucket. Personally I think rate-limiting should be implemented outside `Flask-RESTX`

Thanks @onlinejudge95 
I appreciate your comments

**Comment by successor1** [comment]
> As far as I think, the task of `Flask-RESTX` is to provide a REST Framework for `flask` compatible with `swagger`. I don't see why RATE limiting would fall in this bucket. Personally I think rate-limiting should be implemented outside `Flask-RESTX`

Because there is no working limiter as far as i know.
