### ISSUE TITLE
Orderable and Searchable endpoint

### ISSUE THREAD

**Issue by Aletz-Arce** [python-restx/flask-restx#146]
**Orderable and Searchable endpoint**
Hello, how to implement an endpoint with search and sorting capabilities by specific fields

Thanks

**Comment by onlinejudge95** [comment]
How about creating a `GET /search?q=$QUERY&key=$FIELD` and implement the search algorithm as part of your service. In the same way how about `GET /order?q=$ORDER_KEY`

**Comment by Aletz-Arce** [comment]
> How about creating a `GET /search?q=$QUERY&key=$FIELD` and implement the search algorithm as part of your service. In the same way how about `GET /order?q=$ORDER_KEY`

Thanks again
