### ISSUE TITLE
How do I share a model between Namespaces ?

### ISSUE THREAD

**Issue by fnalonso** [python-restx/flask-restx#162]
**Ask a question**
Hi,

I am implementing a simple API with two login URL `admin/login` and `user/login` and both returns the same object containing a access_token and a refresh_token. The best way from my point of view is that I was able to declare the model only one time and use in the resources described, but when I try to import the model from a external file the `ValueError: Model id not registered` occurs.

To illustrate the scenario the structure I am using is something like:

```python
# models.py
from flask_restx import Namespace, fields

models_namespace = Namespace("Models")

auth_model = models_namespace.model('Auth model', {
  'access_token': fields.String(description="JWT access token",
  'refresh_token': fields.String(description="JWT refresh token"
})

# admin_resource.py
from models import auth_model

admin_namespace = Namespace("administration")

admin_namespace.route("/login")
class AdminLogin(Resource):
  @ns.doc("Administration Login", body=login_model)
  @ns.response(200, "", auth_model)
  def post:
    # do login stuff


# __init__.py

from models import models_namespace
from admin_resource import admin_namespace

api.add_namespace(models_namespace)
api.add_namespace(admin_namespace)

```
Is there any way to share models between namespaces ?

Thank you!

**Additional context**

**Comment by fnalonso** [comment]
Just discovered the issue!

In one of my resources I was using the following statement:

```python
class MyResource(Resource):
  @ns.response(200, "", list(SomeModel))
  def get(self):
    # do stuff
```
Just replaced the `list(SomeModel)` by `[SomeModel]` and everything worked.

Tks!!

**Comment by JohnnyChiang** [comment]
Your answer just saved me after multiple hours searching.
Thanks a lot
