### ISSUE TITLE
Not so small application/json response body makes browser hung up?

### ISSUE THREAD

**Issue by ykpark79** [python-restx/flask-restx#167]
I am currently implementing GET REST API with query parameters which gives large amount of JSON response body.
(it is not significantly large but not so small)
It return like below after I run "try it out. 
![image](https://user-images.githubusercontent.com/29969691/86242452-b6f78f80-bbdf-11ea-923a-53d9ff350a04.png)
Which works okay.
Response from server doesn't take so much time to send back the response. (below 200ms)

When scrolling down on "response payload" section on the document page, then if I want to move other area of the document,
browser is hung up for around 4 seconds.

Without clicking or scrolling in the "response payload", clicking other namespace or API works okay.
But **this only happens when my mouse focused into the "response payload" section in the document page**.

Any idea or help?
Is there any limit in RestX to display in response payload section?

**Comment by vincent-heatseekr** [comment]
In a different life I think I remember a similar sort of issue, but to documentation wasn't generated with Flask-restx. Think it's caused by the implementation of the Swagger JS library.

**Comment by ykpark79** [comment]
@vincent-heatseekr 
thank you for comment. As you pointed out, i found similar issue in Swagger JS as below.
https://github.com/swagger-api/swagger-ui/issues/3832
