### ISSUE TITLE
Email field type?

### ISSUE THREAD

**Issue by gbeane** [python-restx/flask-restx#17]
I think it would be useful to have a email field type, which would be similar to fields.String, but would have a Swagger example value similar to "user@example.com" instead of "string: and would validate that the field contains a properly formatted email address

**Comment by ziirish** [comment]
Hello,

Thanks for the suggestion.
I'm personaly NOT in favour of any "email parser/validator" as I've seen countless website rejecting VALID email addresses I wanted to use.

Now if you are OK with only checking if the provided address contains a `@` sign, then I might considering adding such field.

@SteadBytes, @j5awry any thoughts?

**Comment by j5awry** [comment]
Also against heavy email validation. _however_ having a field that has a default "simple" email validator ("does it have an `@` then a `.`") may be ok. And then if users want to plug in a more specific validator, making that easy ("email address must only use these characters in these spots...").

**Comment by caiquecp** [comment]
What about a regex validator for string type fields?

**Comment by CrazyBonze** [comment]
I agree that at the most a field type for an email should have very basic validation such as an @ and . character but i have had to implement my own field types for uuid, ipv4, ipv6 and time in a format HH:MM:SS. Having an example on how to do this would have saved me some time. Maybe creating a factory or some other design pattern to help with this would be a good idea.

**Comment by SteadBytes** [comment]
@ziirish I agree, reliably validating email addresses is surprisingly non trivial and I don't think specific validators are the responsibility of flask-restplus. I'm sure theres email validation libraries on PyPi which could be pulled in by users if and when it's needed 👍

**Comment by SVilgelm** [comment]
+1 for the waiting, the marshmallow has a really good Email validator: https://github.com/marshmallow-code/marshmallow/blob/709fcbcec6e182885692a0518a1f7caa9c088917/src/marshmallow/validate.py#L129

**Comment by j5awry** [comment]
I think this fits great into adopting Marshmallow. We should start making more concrete plans for redoing the marshalling using a library (ditto for all the request parser stuff...)

**Comment by gbeane** [comment]
If the plan is to adopt Marshmallow in the near future waiting seems like the best option
