### ISSUE TITLE
Marshal not renaming fields with attribute

### ISSUE THREAD

**Issue by voice1** [python-restx/flask-restx#19]
Either I am misunderstanding how to use the marshal feature, and the documentation or the following is a bug.

### **Code**

```
m = api.model('mymodel', {'name': fields.String(attribute='MyName')})
@api.route('/test')
class Test(Resource):
    @api.expect(m)
    def post(self, **kwargs):
        logger.debug(api.payload)
        logger.debug(request.get_json())
        logger.debug(marshal(api.payload, m))
        return api.payload

```
Output
```
127.0.0.1 - - [26/Jan/2020 22:57:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2020 22:57:37] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Jan/2020 22:57:37] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 -
127.0.0.1 - - [26/Jan/2020 22:57:37] "GET /swaggerui/droid-sans.css HTTP/1.1" 304 -
127.0.0.1 - - [26/Jan/2020 22:57:37] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Jan/2020 22:57:37] "GET /swaggerui/favicon-16x16.png HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2020 22:57:37] "GET /swagger.json HTTP/1.1" 200 -
[2020-01-26 22:58:09,111] DEBUG in switchvox: {'name': '987'}
[2020-01-26 22:58:09,111] DEBUG in switchvox: {'name': '987'}
[2020-01-26 22:58:09,111] DEBUG in switchvox: {'name': None}
```

### **Expected Behavior**
I expected that using the fields.String(attribute="...") would cause the rewrite of the data being entered so that instead of receiving {'name': '987'} I would  have received {'MyName': '987'}
Either when calling api.payload or request.get_json()

### **Actual Behavior**
No change in field names.

### **Error Messages/Stack Trace**
Does not error, just does not return expected results.

### **Environment**
- Python 3.7
- Flask version current
- Flask-RESTX version current
- Other installed Flask flask_restplus

Maybe I am calling it wrong, even using marshal() did not return any data. Unfortunately the documentation is not really clear to me around this part.

**Comment by caiquecp** [comment]
I had the same problem, expecting that the result of marshal would have the key/attribute renamed. I had to write a function to do it myself, because the way it is now it is one way only. I think it's a bug.

**Comment by voice1** [comment]
Thought it was just me... good to know. Sadly if I have to write a function to clean it up, then there is no point (IMHO) to use the marshal services, if you just have to do it yourself anyways. D.R.Y. does not seem to apply much here, and feels like lots of overlapping stuff that is a little all over.

**Comment by TeddyTrqt** [comment]
Hello,

I think you inverted the two fields.

Here is the documentation: 
https://github.com/python-restx/flask-restx/blob/master/doc/marshalling.rst#complex-structures

Here is an example:

```python
>>> import json
>>> from flask_restx import fields, marshal
>>> payload = {"name": "test123"}
>>> resource_fields = {'MyName': fields.String(attribute='name')}
>>> json.dumps(marshal(payload, resource_fields))
'{"MyName": "test123"}'
```

**Comment by SteadBytes** [comment]
`attribute` is used to rename an internal object property to the *public* facing property https://github.com/python-restx/flask-restx/blob/master/doc/marshalling.rst#renaming-attributes  when *marshalling*:

```python
m = api.model('mymodel', {'name': fields.String(attribute='MyName')})
@api.route('/test')
class Test(Resource):
    @api.marshal_with(m)
    def post(self, **kwargs):
        logger.debug(api.payload)
        logger.debug(request.get_json())
        logger.debug(marshal(api.payload, m))
        return api.payload
```

Response:
```bash
curl -H "Content-Type: application/json" \
-d '{"MyName": "Ben"}' http://localhost:5000/test
{
    "name": "Ben"
}
```

Log output:
```
[2020-02-15 07:24:51,562] DEBUG in t: {'MyName': 'Ben'}
[2020-02-15 07:24:51,563] DEBUG in t: {'MyName': 'Ben'}
[2020-02-15 07:24:51,563] DEBUG in t: {'name': 'Ben'}
127.0.0.1 - - [15/Feb/2020 07:24:51] "POST /test HTTP/1.1" 200 -
```

**Comment by ianzimmerman** [comment]
> `attribute` is used to rename an internal object property to the _public_ facing property https://github.com/python-restx/flask-restx/blob/master/doc/marshalling.rst#renaming-attributes when _marshalling_:

This doesn't seem to be true (from what you linked:

    model = {
        'name': fields.String(attribute='private_name'),
        'address': fields.String,
    }

**Comment by nadavof** [comment]
Hi, 
Sorry for reopening the issue.
My code is slightly different, but my target is similar to the post's writer. 
I'm struggling to rename the internal attribute to a public attribute. 

My ORM objects look like this (**Flask-SQL-Alchemy**):
```
class Answer(db.Model):
    id = db.Column(db.Integer, unique=True, primary_key=True)
    answer = db.Column(db.Integer, nullable=False)
```
I running this code:
```
answer_resource_fields = {
	'id': fields.Integer,
    'answer': fields.Integer(attribute='private_answer'),

}

class Answers(Resource):
    @marshal_with(answer_resource_fields)
    def get(self):
        '''
        Get all questions from DB
        '''
        result = Answer.query.all()
        return result
```

Output:
{"id": <ID>, "answer": <Answer.answer>}
Expected results:
{"id": <ID>, "**private_answer**": <Answer.answer>}


I tried to search for relevant documentation or example for my case, but I couldn't find any.

Would appreciate it if someone can help: )

Thanks!

**Comment by iamrahulrnair** [comment]
In POST if user is supplying public facing key then upon sending response, we should probably format to change 'answer'  key to RENAMED_ATTRIBUTE.
`return {'RENAMED_ATTRIBUTE':result.answer}`

**Comment by iamrahulrnair** [comment]
> Hi, Sorry for reopening the issue. My code is slightly different, but my target is similar to the post's writer. I'm struggling to rename the internal attribute to a public attribute.
> 
> My ORM objects look like this (**Flask-SQL-Alchemy**):
> 
> ```
> class Answer(db.Model):
>     id = db.Column(db.Integer, unique=True, primary_key=True)
>     answer = db.Column(db.Integer, nullable=False)
> ```
> 
> I running this code:
> 
> ```
> answer_resource_fields = {
> 	'id': fields.Integer,
>     'answer': fields.Integer(attribute='RENAMED_ATTRIBUTE'),
> 
> }
> 
> class Answers(Resource):
>     @marshal_with(answer_resource_fields)
>     def get(self):
>         result = Answer.query.all()
>         return result
> ```
> 
> Output: {"id": , "answer": <Answer.answer>} Expected results: {"id": , "**RENAMED_ATTRIBUTE**": <Answer.answer>}
> 
> I tried to search for relevant documentation or example for my case, but I couldn't find any.
> 
> Would appreciate it if someone can help: )
> 
> Thanks!

In POST if user is supplying public facing key then upon sending response, we should probably format to change 'answer'  key to RENAMED_ATTRIBUTE.
`return {'RENAMED_ATTRIBUTE':result.answer}`
