### ISSUE TITLE
Boolean example, unable to set value to False

### ISSUE THREAD

**Issue by ogenstad** [python-restx/flask-restx#206]
### **Code**

When using a boolean field it's not possible to set the example value to `False`, when viewing the documentation the boolean will always show true.

```python
        "quarantine": fields.Boolean(
            required=False,
            description="Boolean flag indicating if this device is quarantined",
            example=False,
       ),
```

The issue comes from [this line](https://github.com/python-restx/flask-restx/blob/master/flask_restx/fields.py#L159):

```python
        self.readonly = readonly
        self.example = example or self.__schema_example__
        self.mask = mask
```

It could be fixed with something like this:

```python
        self.readonly = readonly
        self.example = example if example is not None else self.__schema_example__
        self.mask = mask
```

### **Expected Behavior**
It should be possible to set the boolean example to both True and False

### **Actual Behavior**
The example always show True.

### **Additional Context**

I'm happy to send in a PR to this if desired.

**Comment by jrreich** [comment]
I can confirm the same bug. The fix from @ogenstad works for me.

**Comment by ziirish** [comment]
Thanks for the report and solution.

I'll try to take some time in the coming weeks. Meanwhile feel free to open a PR otherwise I'll submit a patch when I have a chance.

**Comment by ogenstad** [comment]
Sure I opened #213.

**Comment by ziirish** [comment]
Awesome, thanks!
