### ISSUE TITLE
What is the better way at today to validate and documentate the expected input?

### ISSUE THREAD

**Issue by sanslash332** [python-restx/flask-restx#212]
**Ask a question**
A clear and concise question

At today, what the methods availables and documented is the recomended way to validates and documents the expected input in a endpoint?
api.model, reqparse or marshmallow?
**Additional context**

Simply ask what is the recommended way to do this kind of validation, and what available tool is better to use.
Because the classic decorator @api.expect can receipt a model object, or a reqparse but the latest will be deprecated so...

Can you use api.model and validate with it the input from different locations like querystring, json body, etc like reqparse?
Or is better use reqparse for input, an api.model for marshall output.

Or, use model only for documenting input and output, and a manual parsing using a marshmallow schema?

Sorry for the long question; thanks guys for continuing the awesome project that was flask_restplus

**Comment by ziirish** [comment]
Indeed, reqparse is deprecated and should be removed/replaced at some point in the future. But we don't have any ETA yet nor any alternative for now.

Now you can use the `api.expect()` decorator for input payload validations or `reqparse` for query params.

**Comment by sanslash332** [comment]
OK thanks @ziirish for your answer :)

Well wait to see if in the future appear a better method to documentate inputs, and checks model in ani input method :) thanks!
