### ISSUE TITLE
Using GetHub Actions instead of Travis CI

### ISSUE THREAD

**Issue by SVilgelm** [python-restx/flask-restx#23]
I would like to make a proposal to use GitHub Actions instead of Travis CI.
In my opinion and from my experience, the GitHub Actions works better and a bit faster than Travis CI.
The most important enhancement is that everything is stored on the GitHub.
GitHub workflows allows to test on Linux, Mac and Windows VMs for free for the open source projects.
All developers can test their code in their forks just pushing a code into a brach, open the actions (in there fork, not here) and see the results.

Examples of the Push and Pull Request checks are here: https://github.com/SVilgelm/flask-restx/pull/3/checks
it's a PR to master branch in my fork.

Example of the release workflow: https://github.com/SVilgelm/flask-restx/runs/410117918?check_suite_focus=true
and the pypi: https://pypi.org/project/flask-restx-svilgelm-test/99.99.99/

So, let's discuss.

**Comment by ziirish** [comment]
I answered in #18 so I won't repeat myself here, unless others want to have a discussion.
The TL;DR is I like the idea ;)

**Comment by SVilgelm** [comment]
Closing since the discussion takes place in the PR #18
