### ISSUE TITLE
Nested JSON schemas not showing in Swagger docs

### ISSUE THREAD

**Issue by eboddington** [python-restx/flask-restx#232]
**Ask a question**
Can flask-restx generate Swagger docs based on nested JSON schemas?

**Additional context**
I recently redefined all of my API models using Pydantic and have been using [flask_pydantic](https://github.com/bauerji/flask_pydantic) successfully to handle validation and serialisation/deserialisation.

I'd like to also use these models to generate docs for my API, and have had some limited success by converting them to JSON schemas using the Pydantic `schema()` method. What doesn't seem to work are nested schemas, for example:
```
class Nested(BaseModel):
    id: int = Field(..., example=1)
    name: str = Field(..., example="Nested Item")


class TopLevel(BaseModel):
    id: int = Field(..., example=17)
    short_name: str = Field(..., example="fb")
    name: str = Field(..., example="FOOBAR")
    nested: Nested


schema = TopLevel.schema()
```

`schema` in the example above looks like this:
```
{
  "title": "TopLevel",
  "type": "object",
  "properties": {
    "id": { "title": "Id", "example": 17, "type": "integer" },
    "short_name": { "title": "Short Name", "example": "fb", "type": "string" },
    "name": { "title": "Name", "example": "FOOBAR", "type": "string" },
    "nested": { "$ref": "#/definitions/Nested" }
  },
  "required": ["id", "short_name", "name", "nested"],
  "definitions": {
    "Nested": {
      "title": "Nested",
      "type": "object",
      "properties": {
        "id": { "title": "Id", "example": 1, "type": "integer" },
        "name": { "title": "Name", "example": "Nested Item", "type": "string" }
      },
      "required": ["id", "name"]
    }
  }
}
```

Usage:
```
model = api.schema_model("TopLevel", schema)


@api.response(200, description="blah", model=model)
class MyResource(Resource):
    ...
```

As far as I can tell, this is a valid JSON schema, so I don't think this is an issue related to Pydantic. However, in the Swagger docs I see this:

![Screenshot 2020-10-05 at 15 49 35](https://user-images.githubusercontent.com/3886999/95094950-62a20580-0722-11eb-8240-6e15963d5e1c.png)

![Screenshot 2020-10-05 at 15 49 11](https://user-images.githubusercontent.com/3886999/95094970-659cf600-0722-11eb-84cf-a2ae0568546f.png)

In the API "responses" section, it completely misses out `nested`, and in the "models" section at the bottom of the docs, it shows it as an empty object.

Is anyone successfully using nested JSON schemas to document APIs with `@api.response`?

**Comment by j5awry** [comment]
No, flask-restx cannot do nested JSON schemas at this time. This has been an open issue since the flask-restplus days. There are logic issues in walking the jsonschema tree to create the objects that do not properly handled references.

Though, I have a question -- if you're already using `pydantic` have you looked at `fastapi`? That's built on `pydantic` and provides automatic `OpenAPI` and JSONSchema.

**Comment by eboddington** [comment]
> No, flask-restx cannot do nested JSON schemas at this time. This has been an open issue since the flask-restplus days. There are logic issues in walking the jsonschema tree to create the objects that do not properly handled references.
> 
> Though, I have a question -- if you're already using `pydantic` have you looked at `fastapi`? That's built on `pydantic` and provides automatic `OpenAPI` and JSONSchema.

Thanks for confirming, that's a shame. Yeah, I've looked at FastAPI but this is for an existing project where I felt like migrating to FastAPI would be quite a big task. I guess if we want automatic schema documentation from our models then we might be best off considering it, though.

**Comment by conradogarciaberrotaran** [comment]
Hi @eboddington, did you find any other way to use Pydantic in your restx app and get your swagger docs updated automatically?
Thanks

**Comment by eboddington** [comment]
@conradogarciaberrotaran unfortunately not. We can't find a way to get good docs out of Flask+extensions and it's one reason why we're planning an eventual transition to FastAPI.

**Comment by ddimond-indigo** [comment]
I think this could work as a work-around:
```
def flask_restx_schema(ns: Namespace, pydantic_model: Type[BaseModel]):
    json_schema = jsonref.loads(pydantic_model.schema_json())
    for def_name, def_val in json_schema.get("definitions", {}).items():
        ns.doc(ns.schema_model(def_name, def_val))

    return ns.schema_model(pydantic_model.__name__, json_schema)
```
And usage would be something like
```
class SubModel(BaseModel):
    sub_blah: str

class Model(BaseModel)
    blah: SubModel

@api.response(200, description="blah", model=flask_restx_schema(api, Model))
class MyResource(Resource):
    ...
```

**Comment by gautierrog** [comment]
> 

Unfortunatly, the intermediate models doesn't get created. I'm afraid the ns.doc is only taken in account if it's used as a decorator to some resource (and adding several @ns.doc decorator doesn't work either)

**Comment by toddabrams** [comment]
> I think this could work as a work-around:
> 
> ```
> def flask_restx_schema(ns: Namespace, pydantic_model: Type[BaseModel]):
>     json_schema = jsonref.loads(pydantic_model.schema_json())
>     for def_name, def_val in json_schema.get("definitions", {}).items():
>         ns.doc(ns.schema_model(def_name, def_val))
> 
>     return ns.schema_model(pydantic_model.__name__, json_schema)
> ```
> 
> And usage would be something like
> 
> ```
> class SubModel(BaseModel):
>     sub_blah: str
> 
> class Model(BaseModel)
>     blah: SubModel
> 
> @api.response(200, description="blah", model=flask_restx_schema(api, Model))
> class MyResource(Resource):
>     ...
> ```

Another option:
```
def flask_restx_schema(ns: Namespace, pydantic_model: Type[BaseModel]):
    json_schema = deepcopy(jsonref.loads(pydantic_model.schema_json()))
    return ns.schema_model(pydantic_model.__name__, json_schema)
```
