### ISSUE TITLE
Need to Explicitly set Swagger specs_url Scheme When Deployed on Behind AWS Elastic Load Balancer.

### ISSUE THREAD

**Issue by DustinMoriarty** [python-restx/flask-restx#237]
We have found that when we deploy to AWS ECS behind an elastic load balancer, we need to subclass the API class in order to explicitly set the scheme for the URL such that it sets an external URL instead of a relative URL. It would be preferable if this option was built into flask-restx itself.

I plan to submit a PR for this issue.

**Comment by rdagumampan** [comment]
I hope your PR solves this with ease... Sharing here my solution.

I solved this for AKS with these hacks. This requires that I explicitly set a APP_BASE_PATH settings variable. This ensures that if theres value, then its running behind an ingress controller with custom host path as base URL in SwaggerUI. 

```
class ReverseProxiedApi(Api):
    # handles dynamic root path when running local and on aks cluster
    @property
    def specs_url(self):
        return url_for(self.endpoint('specs'))

    # handles dynamic root path when running local and on aks cluster
    @property
    def base_path(self):
        base_path = get_value("APP_BASE_PATH") or None
        if base_path:
            return base_path
        else:
            return url_for(self.endpoint("root"), _external=False)

api = ReverseProxiedApi(
    version="1.0",
}

# handles dynamic root path when running local and on aks cluster
@apidoc.apidoc.add_app_template_global
def swagger_static(filename):
    base_path = get_value("APP_BASE_PATH") or None
    if base_path:
        return "{0}/swaggerui/{1}".format(base_path, filename)
    else:
        return url_for("restx_doc.static", filename=filename)


# handles dynamic root path when running local and on aks cluster
@api.documentation
def custom_ui():
    base_path = get_value("APP_BASE_PATH") or None
    if base_path:
        return render_template("swagger-ui.html", title=api.title, specs_url="{}/swagger.json".format(base_path))
    else:
        return render_template("swagger-ui.html", title=api.title, specs_url=api.specs_url)

```

**Comment by DustinMoriarty** [comment]
This is issue #238. I don't think I am able to add it as a linked issue.

@rdagumampan : Let me know if this achieves what you are looking for.

**Comment by DustinMoriarty** [comment]
@rdagumampan : I see your point of providing a more general solution using the base url. I will revise accordingly, though I think I may expose the functionality a little differently to make it more integrated.

**Comment by rdagumampan** [comment]
@DustinMoriarty looking forward to it... I just got my hands on Python in last two weeks and lost few hairline on this so If I dont have to hack this way, that would be lovely :D

**Comment by j5awry** [comment]
closing with merge of #238
