### ISSUE TITLE
AssertionError: View function mapping is overwriting an existing endpoint function: api.specs

### ISSUE THREAD

**Issue by proffalken** [python-restx/flask-restx#239]
Hello,

I'm working on an API using Flask (full library versions available below) and Flask-Restx and [importing via Blueprints](https://flask-restx.readthedocs.io/en/latest/scaling.html#use-with-blueprints) with a project structure like so:

```bash
.
├── application
│   ├── apis
│   │   ├── __init__.py
│   │   └── organisations.py
│   ├── app.py
│   └── config.py
└── wsgi.py
```
The code in `app.py` calls a blueprint created in `application/apis/__init__.py` as follows:

**application/apis/__init__.py**
```python
from flask import Blueprint
from flask_restx import Api

from .organisations import api as orgapi

api_v1 = Blueprint('api', __name__)

api = Api(
    api_v1,
    title='My API',
    version='1.0',
    description='Access to my api',
)

api.add_namespace(orgapi)
```
**application/app.py**

```python
# ...
from application.apis import api

# ...
def create_app(config_name):

    app = Flask(__name__)
    # ...
    api.init_app(app)
    # Blueprints
    from application.apis import api_v1 
    app.register_blueprint(api_v1, url_prefix="/api/v1")
```
The `organisations.py` code does not include any views at all, however when I try and access the application, I get the error in the title bar:

**application/apis/organisations.py**
```python
from flask_restx import Namespace, Resource, fields

api = Namespace('organisation', description='Organisation related operations')
```

The only reference I can find to this is a [stackoverflow](https://stackoverflow.com/questions/17256602/assertionerror-view-function-mapping-is-overwriting-an-existing-endpoint-functi) question, and [a github issue dating back to Flask 0.9 vs Flask 0.10](https://github.com/pallets/flask/issues/796), however given how old those questions are I'm pretty confident I'm just holding it wrong!

#### Additional context

**Library Versions (`pip freeze | grep -i flask`)**:
```
Flask==1.1.2
Flask-Admin==1.5.6
Flask-Migrate==2.5.3
flask-restx==0.2.0
Flask-SQLAlchemy==2.4.4
pytest-flask==1.0.0
```

#### Full Stack Trace

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/wsgi.py", line 5, in <module>
    app = create_app(os.environ["FLASK_CONFIG"])
  File "/opt/code/application/app.py", line 54, in create_app
    app.register_blueprint(api_v1, url_prefix="/api/v1")
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1168, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/local/lib/python3.9/site-packages/flask/blueprints.py", line 256, in register
    deferred(state)
  File "/usr/local/lib/python3.9/site-packages/flask/blueprints.py", line 294, in <lambda>
    self.record(lambda s: s.add_url_rule(rule, endpoint, view_func, **options))
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 809, in _blueprint_setup_add_url_rule_patch
    blueprint_setup.app.add_url_rule(
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1282, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: api.specs
```

**Comment by TheLastProject** [comment]
I had this issue and worked around this by adding `add_specs=False` to init_app:

```
api.init_app(app, add_specs=False)
```

Had to look in the source code to find this out: https://github.com/python-restx/flask-restx/blob/7717e481915bafd4aff621642a0fb20b5a380267/flask_restx/api.py#L212

No clue what functionality I may have lost in doing so though...

**Comment by reena4jan** [comment]
@app.route('/', methods=['GET'])
def index():
    # Main page
    return render_template('index.html')


@app.route('/predict', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        # Get the file from post request
        f = request.files['file']

        # Save the file to ./uploads
        basepath = os.path.dirname(__file__)
        file_path = os.path.join(
            basepath, 'uploads', secure_filename(f.filename))
        f.save(file_path)

        # Make prediction
        preds = model_predict(file_path, model)
        result=preds
        return result
    return None


if __name__ == '__main__':
    app.run(debug=True)

I am using this code when i execute this gets some error like
AssertionError: View function mapping is overwriting an existing endpoint function: index  ​

Please let me know how to solve this issue.

**Comment by masete** [comment]
that gives me this 
  mail.init_app(app, add_specs=False)
TypeError: init_app() got an unexpected keyword argument 'add_specs'

**Comment by cSDes1gn** [comment]
> I had this issue and worked around this by adding `add_specs=False` to init_app:
> 
> ```
> api.init_app(app, add_specs=False)
> ```
> 
> Had to look in the source code to find this out:
> 
> https://github.com/python-restx/flask-restx/blob/7717e481915bafd4aff621642a0fb20b5a380267/flask_restx/api.py#L212
> 
> No clue what functionality I may have lost in doing so though...

My guess is you lose on the swagger documentation. I had a similar issue but it was the way I was initializing my API wrapper.

**Comment by froggomad** [comment]
For me I just had to make sure to instantiate api and declare api routes after app routes
