### ISSUE TITLE
Cannot use an array as json body

### ISSUE THREAD

**Issue by autra** [python-restx/flask-restx#253]
# Description

I'm not sure if it's a bug, a feature request or a question. What I want to do is to POST a list of entities to my endpoints, but I'm unable to do so (I can only post objects/dictionnaries). The POST body would therefore look like:

```json
[
    { "id": 1, "foo": "bar", ...},
    { "id": 2, "foo": "baz, ...},
    ...
]
```
I do not want a wrapping dict, even though it is of course a possible workaround.

I cannot manage to achieve such a result. Basically in the code I want to be able to do something like:

```python 
# it could be a fields.Nested instead of a fields.String here
test_fields = api.model('test', fields.List(fields.String))
# or 
test_fields = api.model('test', [fields.String])
# none of these works...

@api.route('/test')
class Tests(Resource):
    @api.expect(test_fields)
    def post(self):
        """
        Test a route
        """
        print('Got length', len(api.payload))
        # then use the array of entities

        return { 'msg': 'success', 'payload': api.payload }
```

**Additional context**

I've managed to achieve such a result, by implementing a ListModel as such:

```python
class ListModel(RawModel, list):

    def __init__(self, name, *args, **kwargs):
        super(ListModel, self).__init__(name, *args, **kwargs)
        self.type = args[0][0]

        def instance_clone(name, *parents):
            return self.__class__.clone(name, self, *parents)

        self.clone = instance_clone

    @property
    def _schema(self):
        return {
                "type": "array",
                "items": self.type.__schema__
        }

    def items(self):
        return [self.type]

    def __deepcopy__(self, memo):
        obj = self.__class__(
            self.name,
            [copy.deepcopy(value, memo) for value in iter(self)],
            mask=self.__mask__,
        )
        obj.__parents__ = self.__parents__
        return obj
```

Did I miss something? If not, would flask-restx be interested in adding such a `ListModel`?

**Comment by andreykurilin** [comment]
A simple workaround: `@NAMESPACE.expect([DICT_MODEL])` . But this thing will allow to provide both a single item and a list of items.

**Comment by autra** [comment]
thanks @andreykurilin this works like a charm! Actually I prefer to be able to post both a single item and a list of items, so that's perfect for me (apart from missing doc, but this feature is not very documented at the moment so...)
