### ISSUE TITLE
Remove default HTTP 200 response code in doc

### ISSUE THREAD

**Issue by mateusz-chrzastek** [python-restx/flask-restx#272]
**Ask a question**
Hi, I was wondering if it's possible to remove the default "200 - Success" response in the swagger.json?

My model:
```
user_model = api.model(
    "User",
    {
        "user_id": fields.String,
        "project_id": fields.Integer(default=1),
        "reward_points": fields.Integer(default=0),
        "rank": fields.String,
    },
)
```

The route:

```
@api.route("/")
class UserRouteList(Resource):

    @api.doc(model=user_model, body=user_model)
    @api.response(201, "User created", user_model)
    @api.marshal_with(user_model, code=201)
    def post(self):
        """Add user"""
        data = api.payload

        return (
            userDB.add(data),
            201
        )
```

**Additional context**
flask-restx version: 0.2.0

![image](https://user-images.githubusercontent.com/34584653/103555872-3593f900-4eb1-11eb-8d29-16f1629489ab.png)

**Comment by chucklin** [comment]
I think the 200 response is added by the following line.
`@api.doc(model=user_model, body=user_model)`

The output model information has been added by the following 2 decorators `@api.response` and `@api.marshal_with`.
I would suggest you modify the `@api.doc` to include `body=user_model` only.
Or use `@api.expect(user_model)` to specify the input model.
Hope this will help.

**Comment by mateusz-chrzastek** [comment]
That worked 👍 Thank you very much!
