### ISSUE TITLE
More Maintainers Means More Goodness!

### ISSUE THREAD

**Issue by j5awry** [python-restx/flask-restx#273]
Our small team hasn't had the bandwidth lately to keep up with flask-restx. And at least a few of us no one longer work as web devs, so we have no day to day usage. 

How do we improve the situation? Get more maintainers!!!

if you're interested in helping with flask-restx, please sign below!

**Comment by hasanul23** [comment]
Hi, I have been using flask-restx at my work. I am interested to contribute to this project. Please, guide me with the necessary details.

**Comment by gabrielmbmb** [comment]
Hi, I've been using `flask-restx` for about 1 year. I would like to help!

**Comment by shashank152k** [comment]
Hello, I'm happy and interested to contribute to this repo. I've been familiar with this project since the flask-restplus days. I've also joined the gitter community.

I just have some queries:
1. Do we have any first-time type issues or is there anything I should do before contributing?
2. Do I just randomly go through the existing issues and try solving them?

Thank you.

**Comment by j5awry** [comment]
Thanks everyone for interest. Just want to clarify, this inquiry isn't about doing PRs and submitting code. as an open source project, anyone can do that already.

What we need is people willing and able to:

1) go through open issues and help triage, test, confirm, and help users
2) validate PRs, offer comments, and help manage PRs (including merging after getting a couple review +1s)
3) help run the release process. Specifically ensuring the changelog is up to date (once that's merged in), running release commands, and ensuring that all build automation is passing
4) engaging with the community on gitter and any other public forums.
5) working on documentation -- it's been pointed out a lot this is a major area of weakness on the project
6) lastly, contributing code

If you're primarily interested in help with code contribution, any and all open issues in the tracker can be tackled. We do have a "good first issue" tag, but it hasn't been used much.

If you've got a contact in GH, we may reach out to you with more specific questions or details.

Thanks!

**Comment by DustinMoriarty** [comment]
@j5awry : I am interested in helping to maintain this project. We use flask-restx at work. However, I have been concerned about whether this project has enough support. I am happy to pitch in with reviewing PR's and general maintenance.

**Comment by asherpasha** [comment]
Me too. We also use flask-restx at work. I am willing to help as much as I can.

**Comment by j5awry** [comment]
Thanks everyone for interest. It's taken a while, but I'm going to send out an email to all those with emails attached to their GH accounts. If you do not have an email in your profile, please send me one ASAP.

From there we'll set up some communication, little background checking, etc. Just need to do quick checks to make sure everyone is on the up and up. Lots of supply chain attacks lately.

**Comment by j5awry** [comment]
Sorry, still getting things sorted. _however_, I think it's worth checking this out:

https://opensource.guide/best-practices/

and remembering that maintenance isn't about contribution. It's more about communication, triage, etc.

**Comment by Abdur-rahmaanJ** [comment]
I hit the walls many times with the docs, i volunteer to help with the docs first

Background:

I have been with Flask for the past 5 years, i might be able to help more but let's see how it goes.

**Comment by j5awry** [comment]
this is open source, and anyone can contribute, anyone can drop into PRs and give reviews. Maintainers are folks with merge and tagging rights. I try to keep Gitter open these days, so anyone can ping me there, and say "I've reviewed X, could you take a look as well to get it merged?" But we need to keep the list of maintainers _generally_ small (as in the group with Github Maintainer rights). 

So I'll ask everyone this -- if you're interested in maintenance, please jump into issues, give feedback, and check out open PRs and give comments. Feel free to @ me on Gitter if you go through a PR and it looks good to move in, and I'll get to it as quickly as a I can to merge it. Once we've gone through a bit of that, we can see about adding more people to Maintainer rights to the repo

I hope everyone understands the need to keep the merge and tag rights to a minimal set of people.

**Comment by cedricbonhomme** [comment]
I see some interesting PRs without any comments or reviews. The dude from the issue #458 is discussing alone. Or the PR #427 about the compatibility issue with new versions of Werkzeug. It's just two examples of contributions from the community.
If someone could just find the time to review, merge some PRs, create a new release, etc. That could be really nice. Or, a maintainer should officially transfer the responsibility of the project. Alternatively give the permission to someone to manage the repository.

**Comment by ziirish** [comment]
Discussion about the future of the project and hence the "recruitment" of new maintainers has moved in #462
