### ISSUE TITLE
conda packages

### ISSUE THREAD

**Issue by mcguipat** [python-restx/flask-restx#28]
Could we get conda packages published?  flask-restplus previous had these publised to conda forge:
https://anaconda.org/conda-forge/flask-restplus 

The feedstock is here:
https://github.com/conda-forge/flask-restplus-feedstock

**Comment by j5awry** [comment]
No one listed as our maintainers are listed in the feedstock. I don't see any official documentation we have for maintaining a conda package. Do you have any experience with getting things setup with Anaconda? I've put out a chat to see if anyone else has info on the Conda package.

**Comment by SVilgelm** [comment]
1. To have a conda-forge package, someone should follow this instruction: https://conda-forge.org/#add_recipe
2. then we the special repo is created, the maintainers should fork that repo under the organization
3. and then we can create an action to automatically update a package on release, but it will require a special GitHub token to push updates, create branches and pull requests.

**Comment by SVilgelm** [comment]
1 ✅ 
Here is a pull request to create the flask-restx recipe: https://github.com/conda-forge/staged-recipes/pull/10742

Please left comment in that PR if you want to be a maintainer of the recipe (leaving a comment is a requirement of the conda-forge project)

@j5awry @ziirish @SteadBytes ^^^

**Comment by mcguipat** [comment]
@SVilgelm I saw your PR was merged, do you have any idea what the process is with conda-forge to build/publish?  I personally am not clear on how this is managed.

**Comment by SVilgelm** [comment]
@mcguipat Could you test the feedstock?
Updating should be easy: https://conda-forge.org/#update_recipe
1. Create new release
2. Update the meta.yml https://github.com/conda-forge/flask-restx-feedstock/blob/master/recipe/meta.yaml
3. Create PR

**Comment by SVilgelm** [comment]
The flask-restx feedstock is created: https://github.com/conda-forge/flask-restx-feedstock

**Comment by mcguipat** [comment]
> @mcguipat Could you test the feedstock?
> Updating should be easy: https://conda-forge.org/#update_recipe
> 
> 1. Create new release
> 2. Update the meta.yml https://github.com/conda-forge/flask-restx-feedstock/blob/master/recipe/meta.yaml
> 3. Create PR

You're describing how to update the feedstock.  I was asking about actually triggering the build/deployment to conda-forge.  That said, it appears it has been done: https://anaconda.org/conda-forge/flask-restx and I would think we can close this issue.

**Comment by SVilgelm** [comment]
As soon as the #18 is merged I can implement the workflow to publish new version, but it requires some configurations from the current maintainers

**Comment by SVilgelm** [comment]
Do not close the issue please. Let's track any needed steps here

**Comment by ziirish** [comment]
Let me know what should be done on our side for the conda release workflow and I'll happily help you out.

**Comment by SVilgelm** [comment]
@ziirish if we want to be able to use the GitHub Action for updating a forge then:
1. Create a fork  https://github.com/conda-forge/flask-restx-feedstock under the python-restx organization
2. Create BOT_TOKEN and BOT_USERNAME secrets with more powerful GitHub token. For first time I would suggest you to generate a Github token, but later It would be better to create a special bot user, `python-restx-bot`, and use its token.
3. I will extend the release action.

Or give me the permissions in organization and I will do the necessary changes

**Comment by SVilgelm** [comment]
@ziirish Thank you for the inviting to the org, but to finish the task with release workflow I need owner permissions to be able to create a bot user and add proper secrets :)
