### ISSUE TITLE
When is version 0.3.0 released (as it is already noted down in CHANGELOG)?

### ISSUE THREAD

**Issue by gro1m** [python-restx/flask-restx#292]
**Ask a question**
When is version 0.3.0 released on pypi? 

**Additional context**
https://github.com/python-restx/flask-restx/blob/master/CHANGELOG.rst seems to indicate that version 0.3.0 is out.

**Comment by j5awry** [comment]
After reviewing some things, I'll push 0.3.0 this week (week of 20210329)

**Comment by j5awry** [comment]
0.3.0 was just released

https://pypi.org/project/flask-restx/
