### ISSUE TITLE
Using semver

### ISSUE THREAD

**Issue by SVilgelm** [python-restx/flask-restx#30]
the latest release of restx is 0.1, the pypi package has 0.1.0, the conda-forge (#28) 0.1.0 (it cannot download the package from pypi using 0.1 version).
So I would recommend to use [semver](https://semver.org) for the releases and always three digest, include tags and releases.

The main problem people have with semver, that if there is a backward incompatible changed, they afraid to increase the major number.

Here is a short summary:
Given a version number MAJOR.MINOR.PATCH, increment the:
* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards compatible manner, and
* PATCH version when you make backwards compatible bug fixes.

**Comment by ziirish** [comment]
semver is very complicated to follow, we are all afraid of that MAJOR version. It's also not that clear whether dropping let's say python 3.4 should be considered a MAJOR or a MINOR change.

But we'll try to stick with the semver *format* as most as we can.

**Comment by SVilgelm** [comment]
It's very easy the incompatible changes then MAJOR. In case of 3.4 the MAJOR should be increased :)
AS I said most developers still afraid to increase the MAJOR tag, but it's just a number, nothing else.
Google Chrome has a version of 80, who cares?

**Comment by ziirish** [comment]
The most complicated part is to get to the 1.0.0
Usually, people expect the 1.0.0 version to be stable, robust, feature-full, etc.

There are plenty of examples out there where it takes 10 to 15 years to get to v1.0.0 (take VLC, wine, etc.)
We should have probably started with 1.0.0, but still have tons of things to achieve for that. We are still a young project (although the codebase is older). I'd like to see if people are following us, and if we answer their needs prior bumping to v1.0.0.

On the other hand, dropping support for python 3.4 is a good opportunity to bump to v1.0.0.

**Comment by SVilgelm** [comment]
I think, dropping support for 2.7 and 3.4.

**Comment by SVilgelm** [comment]
Ok, so let's just have 3 digits tags and it should work with pypi and Conda
