### ISSUE TITLE
How to add the same responses across all namespaces?

### ISSUE THREAD

**Issue by moshevayner** [python-restx/flask-restx#307]
**Ask a question**
I have a pretty broad API which consists of multiple namespaces, and multiple endpoints for each namespace.
Right now, I'm decorating every endpoint with the same set of responses which are relevant for all of them.
This feels pretty repetitive, and makes me wonder if there might be a better way to do this?

**Additional context**
Every endpoint is decorated for example with 
```python
@api.response(401, "Authentication Failure")
@api.response(500, "Generic Error")
```
I tried looking at using [decorators](https://flask-restx.readthedocs.io/en/latest/api.html#core) in the init of my `Api` object, but that seems tricky, since `doc` or `response` for that matter, are both instance methods of a `Namespace` object, thus I can't simply import them and use them.
Is there an easy way to tell the main api - add these default responses to _every_ endpoint?
Thanks!

**Comment by zhangbin27** [comment]
Hello, have you solved the question? How to do ? I will be glad for your reply, thank you!
