### ISSUE TITLE
ImportError: cannot import name '_endpoint_from_view_func'

### ISSUE THREAD

**Issue by radhasaraf** [python-restx/flask-restx#318]
I recently upgraded my flask version to 2.0.0
I get the following error:
```
  File "/home/radha/data-mining-backend/venv/lib/python3.6/site-packages/flask_restx/api.py", line 20, in <module>
    from flask.helpers import _endpoint_from_view_func
ImportError: cannot import name '_endpoint_from_view_func'
```
flask-restx version: 0.2.0
Related: [flask-restful issue around the same error](https://github.com/flask-restful/flask-restful/pull/915)
PS: I tried upgrading to flask-restx 0.3.0, where the issue persists, whereas flask-restx 0.4.0 is not compatible with flask 2.0.0

**Comment by j5awry** [comment]
This is known. please see #313 and #308 for more information
