### ISSUE TITLE
Flask-restx not supporting latest werkzeug

### ISSUE THREAD

**Issue by jagadeesh32** [python-restx/flask-restx#320]
Hi, 

We upgraded to latest flask==2.0.1, but after upgrade packages pipenv showing this in errors. we have no idea how to solve this.  can you suggest which version wekzeug compatible both latest flask and flask-restx.  

thank you

```
There are incompatible versions in the resolved dependencies:
  werkzeug<2.0.0 (from flask-restx==0.4.0->-r /tmp/pipenv3nost1_mrequirements/pipenv-ptiexa_a-constraints.txt (line 11))
  werkzeug>=2.0 (from flask==2.0.1->-r /tmp/pipenv3nost1_mrequirements/pipenv-ptiexa_a-constraints.txt (line 14))
```

**Comment by gregersn** [comment]
This is related to https://github.com/python-restx/flask-restx/issues/313
