### ISSUE TITLE
why Swagger-ui post not  work

### ISSUE THREAD

**Issue by yuruotong1** [python-restx/flask-restx#336]
when i use try it out, post data is "abc", but curl is not work

![image](https://user-images.githubusercontent.com/31992251/121457713-af895a80-c9da-11eb-93e6-662a2f1148d5.png)
![image](https://user-images.githubusercontent.com/31992251/121457773-cd56bf80-c9da-11eb-9635-8d09cab66db9.png)

**Comment by andreykurilin** [comment]
API you are using accepts a json in requests data with required key 'data'.
Parameter of curl command should look like `-d '{"data": "abc"}'`

**Comment by yuruotong1** [comment]
> API you are using accepts a json in requests data with required key 'data'.
> Parameter of curl command should look like `-d '{"data": "abc"}'`

How can I make it work?

![image](https://user-images.githubusercontent.com/31992251/122014641-f1a70780-cdf1-11eb-9140-1f8e4b130797.png)

**Comment by yuruotong1** [comment]
My questing is swagger could not put my input in `-d` : 

![image](https://user-images.githubusercontent.com/31992251/122015373-a17c7500-cdf2-11eb-860e-35ba48f505cf.png)
