### ISSUE TITLE
Support to Flask >= 2.0.0

### ISSUE THREAD

**Issue by rmmariano** [python-restx/flask-restx#342]
**Is your feature request related to a problem? Please describe.**

I've just installed flask-restx and I've noticed that Flask version is < 2.0.0.

```
$ pip freeze
aniso8601==9.0.1
attrs==21.2.0
click==7.1.2
Flask==1.1.4
flask-restx==0.4.0
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
MarkupSafe==2.0.1
pyrsistent==0.17.3
pytz==2021.1
six==1.16.0
Werkzeug==1.0.1
```

I would like to suggest a future version that supports Flask >= 2.0.0.

Thank you in advance.

**Comment by Rafiot** [comment]
Yes, see https://github.com/python-restx/flask-restx/issues/313

**Comment by aalokrmb** [comment]
When we can expect the support for Flask 2.x?

**Comment by Rafiot** [comment]
Whenever https://github.com/python-restx/flask-restx/pull/341 is merged, I'd guess.

**Comment by rmmariano** [comment]
Thank you :)

**Comment by j5awry** [comment]
dupes #313

**Comment by aidoc-erang** [comment]
When will this be uploaded to pypi? :)
