### ISSUE TITLE
Model an array of strings to use in response decorator

### ISSUE THREAD

**Issue by santalvarez** [python-restx/flask-restx#354]
How can I model an array of strings and use it in a `response` decorator.
I tried to do it like this but I get an error, is this event possible in flask restx?
```
["hello", "world"]

md = api.model("Array of Strings", fields.List(fields.String(example="hello")))

@api.response(200, "Hello World", md)
```

**Comment by hbusul** [comment]
Maybe you can [define your model using JSON schema](https://flask-restx.readthedocs.io/en/latest/marshalling.html#define-model-using-json-schema).
``` Python
md = api.schema_model("array_of_strings",
                      {
                          "type": "array",
                          "maxItems": 3,
                          "items": {
                              "type": "string"
                          }
                      })
```
[Some array examples](https://cswr.github.io/JsonSchema/spec/arrays/)
