### ISSUE TITLE
Setting the api representation through the namespace

### ISSUE THREAD

**Issue by olinger** [python-restx/flask-restx#36]
### **Code**

```python
from flask_restx import Resource, Namespace
from flask_accepts import accepts, responds

from app.main.service.kick_event_service import get_all_kick_events, save_new_kick_event
from app.main.model.kick_event import KickEventSchema

api = Namespace('kick_event', description='kick event related operations')

@api.route('/')
class KickEventResource(Resource):
    @responds(schema=KickEventSchema, many=True)
    @api.produces(["application/vnd.api+json"])
    #@api.representation('application/vnd.api+json') <- no bueno
    def get(self):
        """List all Kick Events"""
        return get_all_kick_events()
```

### **Expected Behavior**
I am trying to set the content-type of my response header. I am converting my api to JSON-API standard and so I need to use header "content-type:application/vnd.api+json".

### **Actual Behavior**
I saw in the documentation (https://flask-restx.readthedocs.io/en/latest/api.html#flask_restx.Api.representation) that there is the "representation" method which seemed to be what I needed, but adding `@api.representation('application/vnd.api+json')`
to my code gives me error: "Instance of 'Namespace' has no 'representation' member".

### **Error Messages**
"Instance of 'Namespace' has no 'representation' member".

### **Environment**
- Python version : 3.8
- Flask version: 1.1.1
- Flask-RESTX version: 0.1.0
- Other installed Flask extensions: flask-accepts

### **Additional Context**

Digging through the source code I can see that the namespace class and the api class are not the same, and that the "representation" method doesn't exist in the namespace class, so that error makes sense... But I would like to know how (if it's possible) to declare my api using a Namespace, and also be able to call the representation function.

I managed to get what I wanted by changing `DEFAULT_REPRESENTATIONS = [('application/json', output_json)]` to this: `DEFAULT_REPRESENTATIONS = [('application/vnd.api+json', output_json)]` within the api.py file in the source code for the extension, so now ALL my endpoints have the correct header.. But I'd rather be able to pass it the correct way instead of just overriding the default, if possible.

**Comment by uddmorningsun** [comment]
`Api` has `representation` attribute, `Api.representation()` will register new content type to `Api.representations`. So a simple demo:
```
import flask
import collections
from flask_restplus.representations import output_json
from flask_restx import Api, Namespace, Resource

app = flask.Flask(__name__, static_folder=None)
app.url_map.strict_slashes = False
api = Api()

# If you want **only** application/vnd.api+json, uncomment below line. Or, you should add "Accept: application/vnd.api+json" request Header to achieve best matching
# api.representations = collections.OrderedDict()
api.representations["application/vnd.api+json"] = output_json

api.init_app(app, add_specs=False)
ns = Namespace('kick_event', description='kick event related operations')

api.add_namespace(ns)

@ns.route('/')
class KickEventResource(Resource):
    def get(self):
        return ['kick1', 'kick2']
```

**Comment by olinger** [comment]
@uddmorningsun Thank you for the example! Very helpful.
