### ISSUE TITLE
Pytest error handler issue

### ISSUE THREAD

**Issue by Arulanand** [python-restx/flask-restx#362]
I am building API using Flask Restx. I had written a generic exception handler which will throw an error message and code in Json format.

```
@app.errorhandler(APIError)
def handle_invalid_usage(error):
    logger.opt(exception=True).error(error)
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response
```
I am trying to write unit test using pytest for testing error condition(Resource Not Found). My unit test does return only 500 Internal server error (response.status_code) instead of the going through the error handler and returning 404. When I test it directly using Postman it works perfect.

@pytest.fixture(scope="session")
def app():
    app = create_app()
    return app

```
@pytest.fixture
def client(app):
    return app.test_client()

def test_get_sequence_resource_not_found(mocker: MockerFixture, client: FlaskClient):
    mocked = mocker.patch("service.ViewSequenceService.get_sequence")
    mocked.side_effect = ResourceNotFound('Sequence id Not Present')
    response = client.get("/sequence/f15a9f6e-7a1d-4d12-99c3-fb80d4bc98a1")
    json_data = json.loads(response.data)
    assert response.status_code == 404
    assert json_data['payload']['message'] == 'Sequence id Not Present'
    assert json_data['payload']['status'] == 404
```

**Comment by IvoLeist** [comment]
Hello Arulanand,

I just stumbled about your issue. It looks similar to the one I had a few days ago.

For me adding below to `client(app)` has helped:
`app.testing = True`
Maybe for you as well :crossed_fingers: 

So mine looks as follows:

```
@pytest.fixture
def client(app):
    app.testing = True # propagate exceptions to the test client
    test_client = app.test_client()
    return test_client
```

**Comment by Arulanand** [comment]
Made this change and it worked. Thanks.

**Comment by IvoLeist** [comment]
Glad to hear :) @flask-restx maintainers I guess you can close that issue.
Keep up the good work! :v:

**Comment by j5awry** [comment]
Thank you @idchlife . @Arulanand it looks like we need to improve our documentation around testing a bit. We can probably direct users first to the `flask` documentation which mentions instantiating the app with `TESTING:True` (in context of their example app, which uses a factory pattern)

https://flask.palletsprojects.com/en/2.0.x/testing/
