### ISSUE TITLE
Address Werkzeug, Flask, and Python Versions for flask-restx 0.2.0

### ISSUE THREAD

**Issue by j5awry** [python-restx/flask-restx#37]
Werkzeug 1.0 was released Feb 6th and removes py3.4 support.
Flask requires Werkzeug >= 0.15.0, so a default install from scratch will pull WZ 1.0
Flask has moved onto the 1.X series as of mid-2018 but we "allow" 0.8+

Address the large variance and forward motion of flask and werkzeug.

Flask >= 1.0.2 (1.0 and 1.0.1 had bugs. 1.0.2 stayed stable for ayear)
Werkzeug >= 1.0 (yes, forcing forward compatibility with 1.0 series)

remove py34 

Related to #34 and #35

**Comment by ziirish** [comment]
My plan would be to:
1. merge #18 
2. remove python 3.4 from the test-suite and address the above points
3. rebase #35 
4. merge #35 
5. release v0.2.0

**Comment by ziirish** [comment]
Also, we should address those points as soon as possible, since werkzeug 1.0 is now out and the damages are popping everywhere.

The next thing would be to address our dependency automation discussed in #29

**Comment by plowman** [comment]
Hey @ziirish what's the word on version 0.2.0? Is it just waiting on #63 still?

**Comment by ziirish** [comment]
No, I think we can go ahead with 0.2.0We'll setup dependabot for v1.0.0

**Comment by indy-independence** [comment]
> No, I think we can go ahead with 0.2.0We'll setup dependabot for v1.0.0

When do you think 0.2.0 will be released? It sounds like it might be pretty soon and I'm considering if I should wait for it before doing a beta release with dependencies on flask-restx

**Comment by j5awry** [comment]
This is addressed in the version 0.2.0
