### ISSUE TITLE
GHSL-2021-123

### ISSUE THREAD

**Issue by kevinbackhouse** [python-restx/flask-restx#372]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to GHSL-2021-123.

Thank you,  
Kevin Backhouse
GitHub Security Lab

**Comment by ziirish** [comment]
Hello,

Thanks for notifying us about this. I have drafted a Security Advisory and invited you in. Since this is the first time I'm using this tool, let me know if I missed something.

**Comment by ziirish** [comment]
Thanks for your help on that!
I have released a new version with the suggested fix and published the advisory with the requested credits.

Hope everything is good now.

**Comment by MuIsTheTruth** [comment]
There is something VERY wrong here. I have what now appears to be amnesia. An enormous amount of energy is being manipulated and has been communicating with me. it is the only reason I found my way here. And it tells me it more than just my region.
