### ISSUE TITLE
Change Base URL for all endpoints

### ISSUE THREAD

**Issue by Sladerix** [python-restx/flask-restx#389]
Hi guys, i've a question.
I wish to add a base url for my endpoints, the classic "/api/v1".
i tried with:
```
api = Api(app,
          version="1.0",
          title="SmartParking API",
          description="API For SmartParking Project",
          doc='/docs',
          base_url="/api/v1")
```
But the API still respond on "/" and not on "/api/v1/".

What is the right way to do it? Thanks in advance

**Comment by winterwind37** [comment]
Hi, you need to specify the prefix parameter value instead of base_url.
https://github.com/python-restx/flask-restx/blob/master/flask_restx/api.py#L132

**Comment by Sladerix** [comment]
> Hi, you need to specify the prefix parameter value instead of base_url. https://github.com/python-restx/flask-restx/blob/master/flask_restx/api.py#L132

thanks it works :D
