### ISSUE TITLE
Enable bot/action for stale issues?

### ISSUE THREAD

**Issue by safe** [python-restx/flask-restx#425]
**Is your feature request related to a problem? Please describe.**
There are 188 (well, 189 including this) issues open with many being duplicates.

**Describe the solution you'd like**
Enable a bot/actions to remove stale issues, this will help ensure issues that are open are still relevant while also allowing people to easily search for solutions based on "closed" issues.

**Describe alternatives you've considered**
None, why would you?

**Comment by ziirish** [comment]
Having a bot to help triage and keep issues up-to-date is a great idea, but I'm not sure to understand how this would help people find "solutions based on closed issues".

Do you have any bot recommendation?

**Comment by safe** [comment]
> Do you have any bot recommendation?

GitHub Actions is a good one (https://github.com/actions/stale), this covers issues and pull requests.

@probot also has a stale not which is heavily used (https://github.com/probot/stale).

**Comment by safe** [comment]
I'll close this to prevent another stale issue sitting here.  Just a recommendation, won't take long to implement and should reduce the manual effort needed. Happy to help if you need more people as well.
