### ISSUE TITLE
Input payload validation failed error doesn't show up in Swagger UI

### ISSUE THREAD

**Issue by Shiina18** [python-restx/flask-restx#472]
When I pass an illegal input in the `try it out` and press `execute`, nothing happens in the Swagger UI (http://127.0.0.1:5000/) (no response/error message showing up).

```python
import flask  # 2.2.2
import flask_restx  # 0.5.1

app = flask.Flask(__name__)
api = flask_restx.Api(app=app)

ns = api.namespace(name='issue')
model = ns.model(
    name='model',
    model={
        'uppercase': flask_restx.fields.String(example='A', pattern=r'[A-Z]')
    }
)


@ns.route('/')
class Issue(flask_restx.Resource):
    @ns.expect(model, validate=True)
    def post(self):
        return flask.request.json.get('uppercase')


if __name__ == '__main__':
    app.run(debug=True)
```

For example, passing `{'uppercase': 'a'}`, nothing happens in the UI, while `curl` works as expected to receive error message.

```shell
curl -X 'POST' \
  'http://127.0.0.1:5000/issue/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "uppercase": "a"
}'
```

```json
{
    "errors": {
        "uppercase": "'a' does not match '[A-Z]'"
    },
    "message": "Input payload validation failed"
}
```

**Comment by peter-doggart** [comment]
I think this is caused by `swagger-ui` (external package) and not `flask-restx`. The swagger UI does some client validation and doesn't send the request if the JSON is invalid against the Swagger spec.

**Comment by Shiina18** [comment]
Thanks for your reply. I found a [related issue](https://github.com/swagger-api/swagger-ui/issues/5828) in swagger-ui, and it seems that it is not fixed yet.
