### ISSUE TITLE
Release schedule ETA

### ISSUE THREAD

**Issue by zcherry17** [python-restx/flask-restx#474]
Hello,
I've noticed that the compatibility fix for Werkzeug and Flask have been merged.
I was wondering if there is an estimated date for when there will be a release version available
to use and update projects to.

**Comment by ziirish** [comment]
"soon"

No precise ETA but hopefully next week!

**Comment by zcherry17** [comment]
> "soon"
> 
> No precise ETA but hopefully next week!

Thank you, thank you :)

**Comment by alicanyuksel** [comment]
I confirm also this bug that Werkzeug and Flask latest version are not compatible with **restx**.
And I am also waiting for your update.

**Comment by ziirish** [comment]
Sorry I have a lot of strong deadlines related to both personal and professional projects but the next release is not so far on my TODO list and I'll do my best to do it by the end of the week. :crossed_fingers:

**Comment by ziirish** [comment]
Meanwhile, as stated in #462 a few people joined the project and will progressively make plan to give the project the love it deserves :heart:

**Comment by carlosvega** [comment]
Any news? Thanks!

**Comment by ziirish** [comment]
Sorry, I couldn't find the requested time earlier but I finally managed to fix the CI, review some PRs and _dry run_ the release script so I promise the next release will come pretty soon!

**Comment by rokam** [comment]
I'm anxious for the werkzeug fix. I do think that a more frequent release rate would be great.

**Comment by ziirish** [comment]
Version 1.0.1 has just been released. Please carefully review the [changes](https://github.com/python-restx/flask-restx/blob/master/CHANGELOG.rst#101). This is indeed a major release due to the fact support for python < 3.7 has been dropped.
