### ISSUE TITLE
Custom swagger doc using api.doc 

### ISSUE THREAD

**Issue by BrikerMan** [python-restx/flask-restx#48]
Hi, all~ Thanks for this awesome project.

I need to document a request JSON body using custom YAML rather than defining  a model every time.
This is what I have tried.

```python
POST_BODY_DOC = """
consumes:
  - application/json
parameters:
  - in: body
    name: user
    description: The user to create.
    schema:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
"""

@api .route('/app/demo')
class DemoAPI(Resource):
    @api.doc(**yaml.load(POST_BODY_DOC))
    def post(self):
          .....
```

**Comment by j5awry** [comment]
I see the PR which is for a more generic case of passing in a dict. It's great you're using restx for this, but, I do have to wonder -- if you're starting with API Spec done in YAML, why not use connexion or another "documentation first" framework. with Restx, working in this fashion you're not going to get validation, marshalling, etc.

**Comment by BrikerMan** [comment]
I want to a light API with basic document, but don't want to prepare a model definition for all responses, since in real life API response might be more complex and not easy to define for reusable models. So for me, restx + some Yaml docs are good enough. I use Yaml format because it is more readable than python dict or JSON.

**Comment by BrikerMan** [comment]
The defining model process will become very annoying when I use a JSON as the request body.

**Comment by j5awry** [comment]
One other thing to consider -- restx is meant to support direct JSONSchema instantiations of models. if the yaml jsonspec matches a JSONSchema once turned into a dict, it _should_ work going directly into a model. There are some issues regarding direct JSONSchema conversion though (mainly related to references). 

Also, it may be handy to create a way to generate models from a complex dict directly. 

For an intro, I think this is a value add for cases that want documentation without marshalling or validation.

**Comment by SteadBytes** [comment]
Unless I've misunderstood the issue, it seems that it only uses `flask-restx` to tie a pre-defined schema to a route in the full application schema - no validation, schema generation from models etc. Most of the API provided by `flask-restx` is (at least currently) intended to abstract away from Swagger/OpenAPI specs directly ( hence the `api.doc`, `api.header`, `api.expect decorators`.

Consuming a more complete Swagger/OpenAPI schema directly instead of using those is not necessarily a bad thing in general, but it is quite a shift from that API.

**Comment by BrikerMan** [comment]
@SteadBytes I have lots of not reusable response schema, which I don't want to define as a Model, just want to tell the client how the response will be. So, that is why I wish to have this function. And I have changed the implementation so that it only rewrites the defined keys.

I think this can be a good extension of restx

POST_BODY_DOC = """
raw_doc_keys:
   - consumes
   - parameters
consumes:
  - application/json
parameters:
  - in: body
    name: user
    description: The user to create.
    schema:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
"""

@api .route('/app/demo')
class DemoAPI(Resource):
    @api.doc(**yaml.load(POST_BODY_DOC))
    def post(self):
          .....

**Comment by SteadBytes** [comment]
I understand your use case 😊 However, my point is that (in my view) this diverges from the functionality that `flask-restx` provides as it is manually creating Swagger specs without utilising the models and marshalling API.

If other users and/or maintainers think differently then by all means we can consider it! It's just a car of how it fits and interacts with the existing API and whether it provides enough value for other users to be maintained😊 @ziirish , @j5awry any thoughts?

**Comment by j5awry** [comment]
Sorry for taking a while to circle back. There is already a way to do a raw jsonschema dict -> model. I'd argue that starting from OpenApi Spec in Yaml is a break in the opinionated workflow of flask-restx. As I tossed in earlier, there are specific frameworks for that workflow (like `connexion`). I'm also not sure about a doc only change to accept dicts. I'd say a proper workflow for people _wanting_ to start from an OpenApi Yaml spec is to use the `Raw` model or something similar. So in pseudocode:

```
YAML_SPEC = """
raw_doc_keys:
   - consumes
   - parameters
consumes:
  - application/json
parameters:
  - in: body
    name: user
    description: The user to create.
    schema:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string


MyModel = Raw(yaml.loads(YAML_SPEC))

@api.doc(MyModel)
MyEndpoint(Resource):
     def get():
```

or having a very specific From_Yaml Model that expects an API spec. I'd see _that_ as more of an add-on, though it gets into the space of something like `connexion`...which isn't necessarily a bad thing

**Comment by BrikerMan** [comment]
@j5awry Thanks for the reply, I will try the `RAW` model. And the reason I haven't use other add-ons like `connexion` is that I had already defined some models using flask-restx. I don't need defined models for all the API, only for some of them.

**Comment by BrikerMan** [comment]
I tried the RAW/RAWModel, not work as I expected. I will try to implement the #49 more elegant.
