### ISSUE TITLE
How do I document the required header in and endpoint, when I'm passing a model to expect() instead of a regparse?

### ISSUE THREAD

**Issue by db0** [python-restx/flask-restx#480]
Regparser is not good at documented nested models, so I have switched to passing a model into the `@api.expect()` decorator 

`@api.expect(models.input_model_request_generation, validate=True)`

However that does not document my headers. 

For headers, the documentation says the following

![image](https://user-images.githubusercontent.com/296513/195031594-4303e7d8-677e-4da3-8a49-e691852cc9d0.png)

But I cannot use both parser and model to document. Passing parser to a subsequest `@api.doc()` decorator doesn't seem to work either.

How do I document the expected headers when using models in `expect()` ?

**Comment by peter-doggart** [comment]
Can you define the body as the model and a reqparser in `api.doc` like this old post over on restplus? Not at my computer to test it!:
https://github.com/noirbizarre/flask-restplus/issues/511#issuecomment-471771892

**Comment by db0** [comment]
This seems to work! Thanks!
