### ISSUE TITLE
How to programmatically define the swagger docstring of an endpoint without explicitly typing it in the function docstring?

### ISSUE THREAD

**Issue by svein-izy** [python-restx/flask-restx#498]
I have the following endpoint:
```
@api.route('/users')
class RootUsers(Resource):
    @jwt_required()
    @api.expect(token_args)
    @api.response(200, 'Success')
    @api.response(500, 'Error')
    def get(self):
        """ Get all users """
        return get_all_users()
```

Which in swagger results in the following:
![image](https://user-images.githubusercontent.com/93512824/207353488-2243dea0-86ab-4c62-9ec3-5df1c5c5f5cc.png)

Lets call the part in swagger that says "Get all users" for endpoint docstring.

Now, any attempt to alter the function docstring "Get all users" (for example with `f""" Get all users - {var}"""`) results in the the following swagger result:
![image](https://user-images.githubusercontent.com/93512824/207354269-a4ad8279-d3c7-4d4d-8ad6-452150a45853.png)

The endpoint docstring simpy disappears.

This is my question:
Is there any way I can define the endpoint docstring (for example as an argument to the def get(self) function) so that it renders correctly in swagger?

**Comment by peter-doggart** [comment]
@svein-izy Can I ask what the use case for doing this is?

**Comment by svein-izy** [comment]
@peter-doggart It works, thanks! :)
