### ISSUE TITLE
Flask-RestPlus drop in replacement milestone

### ISSUE THREAD

**Issue by CrazyBonze** [python-restx/flask-restx#50]
After the werkzeug issue #35 that also hit Flask-RestPlus I thought about jumping over to Flask-RestX but i am not sure how stable or close this fork is to the original. I am assuming release 1.0 is the goal for a drop in replacement with only bug fixes and no API breaking changes right? I is safe to move over now?

**Comment by ziirish** [comment]
We forked the project at the point it was at the time.So except the renaming we believe Flask-RESTX is a drop in replacement and therefore at least as stable.The v1.0.0 will drop support for python 3.4 and python 2 so we are going to break things for sure but it's now time to move on.

**Comment by CrazyBonze** [comment]
Awesome, thanks for the clarification. I appreciate the work you guys are doing and hopefully the community can keep the ball rolling for this library. I am interesting in contributing now that progress is being made.

**Comment by SVilgelm** [comment]
Closing the issue since it's answered
