### ISSUE TITLE
Feature request: Models based on dataclasses

### ISSUE THREAD

**Issue by dillondaudert** [python-restx/flask-restx#51]
I'm interested in this feature, so I'm re-opening this [issue](https://github.com/noirbizarre/flask-restplus/issues/709) for flask-restx (@casparjespersen): 

> Since Python 3.7 `dataclasses` was introduced. This is an easy way to define data models:
> 
> ```python
> from dataclasses import dataclass
> 
> @dataclass
> class Foo:
>    name: str
>    age: int
> 
> @dataclass
> class Bar:
>    foo: Foo
> 
> bar = Bar(Foo("Jane Doe", 42))
> ```
> 
> There is a growing eco-system around this, e.g. [the `jsons` module](https://github.com/ramonhagenaars/jsons) that allows (de)serialization of such objects:
> 
> ```python
> import jsons
> 
> bar_dict = jsons.dump(bar)
> assert isinstance(bar_dict, dict)
> 
> bar_again = jsons.load(bar_dict, cls=Bar)
> assert isinstance(bar_again, Bar)
> ```
> 
> It would be interesting to have a discussion on supporting dataclasses as valid model types in flask-restplus, since it is a Python-native data structure (compared to e.g. marshmallow), but it appears (to my knowledge?) to lack validation metadata, etc.

**Comment by SVilgelm** [comment]
@sloria Do you have any plans to use data classes in marshmallow?

**Comment by SVilgelm** [comment]
The main reason to migrate for marshmallow is having a better validation. Or we can generate a openapi/swagger schema but using the jsonschema draft 7 for validation

**Comment by SVilgelm** [comment]
and it requires to drop support for python <= 3.6

**Comment by sloria** [comment]
> @sloria Do you have any plans to use data classes in marshmallow?

There's some discussion of it in https://github.com/marshmallow-code/marshmallow/issues/1411 .

For dataclass->Schema generation, there's already https://github.com/lovasoa/marshmallow_dataclass as well as https://github.com/python-desert/desert (which I'm less familiar with but has similar functionality).

**Comment by SVilgelm** [comment]
Thank you!

**Comment by SVilgelm** [comment]
I think we are not ready to drop support for python 3.5 and 3.6
@ziirish @SteadBytes any thoughts?

**Comment by ziirish** [comment]
I agree, there is no plan yet to drop support for python 3.5 and 3.6

The plan for now is to drop support for python <= 3.4 (including python 2)

https://github.com/lovasoa/marshmallow_dataclass seems like a nice way to address this although we still need to support marshmallow based models.

**Comment by SVilgelm** [comment]
Then let's close issue

**Comment by ziirish** [comment]
Although we probably won't address this particular request in a near future, I think we could still document a workaround based on https://github.com/lovasoa/marshmallow_dataclass once we support it.

Shouldn't we keep this open until then?

**Comment by SVilgelm** [comment]
Nope, I think as soon as the RestX supports the marshmallow, we can think about the datacalssses. but anyway I don't think we will drop support for python 3.5 and 3.6 anytime soon
