### ISSUE TITLE
Using tokenless Codecov action

### ISSUE THREAD

**Issue by SVilgelm** [python-restx/flask-restx#53]
Replace the Coveralls Travis CI and GitHub Actions Yes step with Codecov action when they implemented the tokenless upload: https://github.com/codecov/codecov-action/issues/29

**Comment by SVilgelm** [comment]
/remind me to check the status of action on next Monday

**Comment by ziirish** [comment]
We can give it a new try now.

**Comment by SVilgelm** [comment]
Sure, I will do it
