### ISSUE TITLE
Blueprint example fails to run without issues

### ISSUE THREAD

**Issue by bjarneh** [python-restx/flask-restx#541]
### **Repro Steps**
1. Run the example  [todo_blueprint.py](https://github.com/python-restx/flask-restx/blob/ad2210ce55ec1597639831631632c0019be826e8/examples/todo_blueprint.py)
2. Warnings printed, that will soon become exceptions.

### **Expected Behavior**
The *hello world blueprint* example is expected to run without issues.

### **Actual Behavior**
The blueprint is re-registered, producing warnings (soon exceptions)

### **Error Messages/Stack Trace**

    /home/bjarne/.local/lib/python3.10/site-packages/flask_restx/api.py:322: UserWarning: The setup method 'add_url_rule' can no longer be called on the blueprint 'api'. It has already been registered at least once, any changes will not be applied consistently.
    Make sure all imports, decorators, functions, etc. needed to set up the blueprint are done before registering it.
    This warning will become an exception in Flask 2.3.
      app_or_blueprint.add_url_rule(self._doc, "doc", self.render_doc)
    /home/bjarne/.local/lib/python3.10/site-packages/flask/blueprints.py:491: UserWarning: The setup method 'record' can no longer be called on the blueprint 'api'. It has already been registered at least once, any changes will not be applied consistently.
    Make sure all imports, decorators, functions, etc. needed to set up the blueprint are done before registering it.
    This warning will become an exception in Flask 2.3.
      self.record(
    /home/bjarne/.local/lib/python3.10/site-packages/flask_restx/api.py:323: UserWarning: The setup method 'add_url_rule' can no longer be called on the blueprint 'api'. It has already been registered at least once, any changes will not be applied consistently.
    Make sure all imports, decorators, functions, etc. needed to set up the blueprint are done before registering it.
    This warning will become an exception in Flask 2.3.
    app_or_blueprint.add_url_rule(self.prefix or "/", "root", self.render_root)
     * Serving Flask app 'todo_blueprint'
     * Debug mode: on

### **Environment**
- Python 3.10.6
- Flask 2.2.2
- Flask-RESTX 1.0.3

**Comment by peter-doggart** [comment]
Can you try on Flask-RESTX v1.0.5 or above? This warning is caused by an underlying change to flask which should have been patched in v1.0.5 (current version is 1.1.0).

**Comment by bjarneh** [comment]
Updated Flask-RESTX to latest version I got from 'pip' (**v1.1.0**), runs without issues now. Thanks! I'll close the issue.
