### ISSUE TITLE
test_media_types_method - Test failure

### ISSUE THREAD

**Issue by darless** [python-restx/flask-restx#547]
Latest github actions run with failure:
https://github.com/python-restx/flask-restx/actions/runs/5385063797/jobs/9773681086

### Failure seen

```
self = <test_api_legacy.APITest object at 0x7f26f63ece50>, app = <Flask 'tests.conftest'>, mocker = <pytest_mock.plugin.MockerFixture object at 0x7f26f5f815b0>

    def test_media_types_method(self, app, mocker):
        api = restx.Api(app)
    
        with app.test_request_context(
            "/foo", headers={"Accept": "application/xml; q=.5"}
        ):
>           assert api.mediatypes_method()(mocker.Mock()) == [
                "application/xml",
                "application/json",
            ]
E           AssertionError: assert ['application/json'] == ['application...ication/json']
E             At index 0 diff: 'application/json' != 'application/xml'
E             Right contains one more item: 'application/json'
E             Use -v to get the full diff

tests/legacy/test_api_legacy.py:113: AssertionError
```

### Reproduce
Looks like all python versions are failing in the same way.

```
python3 -m venv venv
. ./venv/bin/activate
pip3 install -r requirements/dev.txt
tox
```

### **Expected Behavior**
Tests expects to see mediatypes as both application/json and application/xml

### **Actual Behavior**
Test only sees application/json

### **Environment**
```
$ pip3 list
Package           Version
----------------- -------
black             23.3.0 
cachetools        5.3.1  
chardet           5.1.0  
click             8.1.3  
colorama          0.4.6  
distlib           0.3.6  
filelock          3.12.2 
mypy-extensions   1.0.0  
packaging         23.1   
pathspec          0.11.1 
pip               20.0.2 
pkg-resources     0.0.0  
platformdirs      3.8.0  
pluggy            1.2.0  
pyproject-api     1.5.2  
setuptools        44.0.0 
tomli             2.0.1  
tox               4.6.3  
typing-extensions 4.6.3  
virtualenv        20.23.1
```

### Additional info

Failure started about 3 weeks ago:

![failure_started](https://github.com/python-restx/flask-restx/assets/3382617/21e5bcc5-89b3-4069-bed9-de038ceb50d7)

From what I can see nothing changed in the repo since March. Looking at the good run and the bad run, the only differences are:
- Werkzeug (Good: 2.3.4, Bad: 2.3.5)
- urllib (Good: 2.0.2, Bad: 2.0.3)

Changing urllib to the old version didn't fix it.
Changing Werkzeug to the old 2.3.4 version fixed the failure.

Werkzeug 2.3.5 changlog: https://werkzeug.palletsprojects.com/en/2.3.x/changes/#version-2-3-5

**Comment by darless** [comment]
Werkzeug changelog for 2.3.5:
https://werkzeug.palletsprojects.com/en/2.3.x/changes/#version-2-3-5

**Comment by darless** [comment]
From 2.3.5 changelog the culprit is likely:

Improper Content-Length Parsing [Werkzeug - 2716](https://github.com/pallets/werkzeug/issues/2716)

**Comment by peter-doggart** [comment]
@darless Thanks for bringing this to my attention and the suggested fixes. For some reason, I didn't get notified by the build system! I will try and get it patched tomorrow. :)

**Comment by chipndell** [comment]
Change in Werkzeug 2.3.5 as [issued here](https://github.com/pallets/werkzeug/issues/2716) caused the fail in build. As per [HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110#section-12.5.1) the quality-factor for HTTP Accept Header has to be like X.X. So changing them all to such format, all Unit tests and Tox test passes.

Also posted a PR for review. :-)

**Comment by peter-doggart** [comment]
@chipndell Thanks for the PR, I never quite got the time to fix as I had planned!
