### ISSUE TITLE
use black to enforce codestyle

### ISSUE THREAD

**Issue by ziirish** [python-restx/flask-restx#55]
Any thoughts on using [black](https://github.com/psf/black) in order to enforce a coding style?

This way we don't have to bother our contributors with a codestyle, they just have to run black prior submitting a PR.

**Comment by SVilgelm** [comment]
I like it, I already have the GitHub Actions to enforce black code style: https://github.com/sv-tools/marshmallow-objects/blob/master/.github/workflows/test.yml#L35

**Comment by SVilgelm** [comment]
It's going to be a huge diff:
```diff
git di --stat
 doc/conf.py                             |  258 ++++++++--------
 examples/todo.py                        |   72 ++---
 examples/todo_blueprint.py              |   74 ++---
 examples/todo_simple.py                 |    9 +-
 examples/todomvc.py                     |   65 +++--
 examples/xml_representation.py          |   20 +-
 examples/zoo/__init__.py                |    6 +-
 examples/zoo/cat.py                     |   33 ++-
 examples/zoo/dog.py                     |   33 ++-
 flask_restx/__about__.py                |    6 +-
 flask_restx/__init__.py                 |   44 +--
 flask_restx/_http.py                    |  245 +++++++++-------
 flask_restx/api.py                      |  420 +++++++++++++++-----------
 flask_restx/apidoc.py                   |   22 +-
 flask_restx/cors.py                     |   40 ++-
 flask_restx/errors.py                   |   23 +-
 flask_restx/fields.py                   |  399 +++++++++++++++----------
 flask_restx/inputs.py                   |  266 +++++++++--------
 flask_restx/marshalling.py              |   44 ++-
 flask_restx/mask.py                     |   82 +++---
 flask_restx/model.py                    |  122 ++++----
 flask_restx/namespace.py                |  182 +++++++-----
 flask_restx/postman.py                  |  169 ++++++-----
 flask_restx/representations.py          |    6 +-
 flask_restx/reqparse.py                 |  221 ++++++++------
 flask_restx/resource.py                 |   24 +-
 flask_restx/schemas/__init__.py         |   45 +--
 flask_restx/swagger.py                  |  499 ++++++++++++++++---------------
 flask_restx/utils.py                    |   43 +--
 setup.py                                |  105 +++----
 tasks.py                                |  185 ++++++------
 tests/benchmarks/bench_marshalling.py   |   28 +-
 tests/benchmarks/bench_swagger.py       |   58 ++--
 tests/conftest.py                       |   40 +--
 tests/legacy/test_api_legacy.py         |  201 +++++++------
 tests/legacy/test_api_with_blueprint.py |  127 ++++----
 tests/test_accept.py                    |  102 ++++---
 tests/test_api.py                       |  227 ++++++++-------
 tests/test_apidoc.py                    |  120 ++++----
 tests/test_cors.py                      |   39 +--
 tests/test_errors.py                    |  373 ++++++++++++------------
 tests/test_fields.py                    | 1162 ++++++++++++++++++++++++++++++++++++------------------------------------
 tests/test_fields_mask.py               | 1058 ++++++++++++++++++++++++++++--------------------------------------
 tests/test_inputs.py                    | 1251 +++++++++++++++++++++++++++++++++++++++++++-----------------------------------
 tests/test_logging.py                   |   32 +-
 tests/test_marshalling.py               |  571 +++++++++++++++++++-----------------
 tests/test_model.py                     |  757 ++++++++++++++++++-----------------------------
 tests/test_namespace.py                 |  142 ++++-----
 tests/test_payload.py                   |  285 +++++++++---------
 tests/test_postman.py                   |  313 ++++++++++----------
 tests/test_reqparse.py                  |  915 +++++++++++++++++++++++++++++----------------------------
 tests/test_schemas.py                   |   32 +-
 tests/test_swagger.py                   | 3590 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------------------------------------------------------
 tests/test_swagger_utils.py             |  173 +++++------
 tests/test_utils.py                     |  114 +++-----
 55 files changed, 7798 insertions(+), 7674 deletions(-)

```

**Comment by cal97g** [comment]
Black is an excellent tool. I think the pro's are:

- Reduces bikeshedding (this is the biggest +)
- Improves readability and standardisation

It's a big diff which is a shame but if we're going to do it early in the project would be the best time, right?

**Comment by SVilgelm** [comment]
if we want to have a black, we need to decide what line length we need?
* pep8 default is 79
* black's default is 87
* also some projects are using 120

I would recommend 120, I'm using it on several projects and it works great.

**Comment by ziirish** [comment]
I'm personally OK with black's default.

The purpose of using black is that we don't have to care with all the details. You write the code the way you like and then you invoke black prior committing your changes.

**Comment by SVilgelm** [comment]
@ziirish I've created the PR: https://github.com/python-restx/flask-restx/pull/60

**Comment by SVilgelm** [comment]
we also need to adjust linter

**Comment by SVilgelm** [comment]
so the problems I found with black.
1. It requires python >= 3.6 to run.
2. it cannot be installed in pypy3 env, due to `typed-ast` module isn't compatible with pypy3: https://github.com/psf/black/issues/727

So to fix all of those problems, I introduced new (first) step in the workflow: checks
It uses only py3.8 to run the checks, like black formatting or any other, what doesn't need to be run on different python versions.

**Comment by SVilgelm** [comment]
Also, I move some requirements from develop.pip to test.pip

**Comment by SVilgelm** [comment]
One more, now we have the flake8 configured for 120. We can add `pyproject.toml` with:
```toml
[tool.black]
line-length = 120
```
and it will work as expected, the `black .` command will reformat everything with 120

**Comment by SVilgelm** [comment]
It will reduce the number of lines for ~1500:
55 files changed, 6269 insertions(+), 7744 deletions(-)

**Comment by SVilgelm** [comment]
One more, the black just a formatter, and the ast is same after the black was run, I think we still need to use a linter, maybe pylint, because it validates a bit more, than the correct code style.

**Comment by SVilgelm** [comment]
So, Let's vote ;-)

❤️ for 120
👍 for 88
👎 for 79

😈

**Comment by SVilgelm** [comment]
@ziirish @SteadBytes @j5awry ^^^^?

**Comment by SteadBytes** [comment]
Yep, 100% do it. It doesn't need to run in all the envs in the test suite. I've had success adding it as a pre-commit hook https://pre-commit.com/ to which keeps everything formatted when a commit is made. Then on CI the hooks can be run in a single environment.

**Comment by SVilgelm** [comment]
so, 88 has more votes, then I don't need to change anything in the current PR #60, let's merge it
