### ISSUE TITLE
How do I manually enter the request header Authorization in the Swagger document

### ISSUE THREAD

**Issue by miaokela** [python-restx/flask-restx#551]
**Ask a question**
How do I manually enter the request header Authorization in the Swagger document

**Additional context**
I need the token to carry when verifying the interface

**Comment by peter-doggart** [comment]
You need to configure flask-restx Swagger security, see the docs here: https://flask-restx.readthedocs.io/en/latest/swagger.html#documenting-authorizations 

There is also a great tutorial for flask-restx that details how to configure JWT like tokens, but it can be used for any authentication scheme in a simialr way: https://aaronluna.dev/series/flask-api-tutorial/part-4/#swagger-ui

**Comment by miaokela** [comment]
<img width="1437" alt="image" src="https://github.com/python-restx/flask-restx/assets/30903265/f444fb81-8694-4dc1-b3f3-c4c4226b28bc">
I have implemented the problem of submitting a Token in the request header in the document by using the parser location as the header, along with ns.expect()
