### ISSUE TITLE
Swagger documentation behind a reverse proxy with subpaths

### ISSUE THREAD

**Issue by alexlopezc** [python-restx/flask-restx#58]
When deploying a service behind a proxy reverse (Traefik) and under a subpath domain (https://api.example.com/service1) swagger.json and swagger-ui sources are not available since flask-restx is looking for them in the root url (https://api-example.com/swagger.json).

My current solution is to set an environment variable for the subpath domain and redefining where the files are located:

```python
    if Config.URL_SUBDOMAIN:
        @apidoc.apidoc.add_app_template_global
        def swagger_static(filename):
            return "{0}/swaggerui/{1}".format(Config.URL_SUBDOMAIN, filename)

    api = Api(app=app, doc='/doc', version=version(), title="API documentation")

    if Config.URL_SUBDOMAIN:
        @api.documentation
        def custom_ui():
            return render_template("swagger-ui.html", title=api.title, specs_url="{}/swagger.json".format(Config.URL_SUBDOMAIN))
```

With this solution the access to the documentation is available but we can not execute the queries from swagger-ui since it does not now anything about the subpath domain.

Flask-restx and swagger-ui should respect the full url where the api is being served.

**Comment by mihailefter** [comment]
Would this be an equivalent for [#223](https://github.com/noirbizarre/flask-restplus/issues/223) in flask-restplus?

**Comment by maesgeert** [comment]
I have the same issue when hosting the API on a port other than 80. Swaggerui keeps the correct path, but Swagger doesn't. 

![err](https://user-images.githubusercontent.com/52412247/74938477-63ce2e80-53ee-11ea-8647-5b342574ca73.png)

**Comment by viliusgudziunas** [comment]
Any updates on this?

**Comment by mikaelmeulle** [comment]
hello,
there is a solution  to make it work behind a reverse  proxy like traefik.
You need to add some   http headers  when forwarding the HTTP requests to flask (for example with a traefik middleware) and use a code like this:

```
from werkzeug.middleware.proxy_fix import ProxyFix

flask = Flask(...)
flask.wsgi_app = ProxyFix(flask.wsgi_app, x_proto=1, x_port=1, x_for=1, x_host=1, x_prefix=1)
```

in this example, will set up different HTTP headers to indicate a custom scheme, port, host and prefix:

x_for – Number of values to trust for X-Forwarded-For.
x_proto – Number of values to trust for X-Forwarded-Proto.
x_host – Number of values to trust for X-Forwarded-Host.
x_port – Number of values to trust for X-Forwarded-Port.
x_prefix – Number of values to trust for X-Forwarded-Prefix.

see [https://werkzeug.palletsprojects.com/en/1.0.x/](https://werkzeug.palletsprojects.com/en/1.0.x/)

**Comment by viliusgudziunas** [comment]
Hi @mikaelmeulle 

Would I have to do the same behind an nginx reverse proxy?

Sorry I am not very good at understanding  how proxies work and what some of these headers actually do.

**Comment by alexlopezc** [comment]
> hello,
> there is a solution to make it work behind a reverse proxy like traefik.
> You need to add some http headers when forwarding the HTTP requests to flask (for example with a traefik middleware) and use a code like this:
> 
> ```
> from werkzeug.middleware.proxy_fix import ProxyFix
> 
> flask = Flask(...)
> flask.wsgi_app = ProxyFix(flask.wsgi_app, x_proto=1, x_port=1, x_for=1, x_host=1, x_prefix=1)
> ```
> 
> in this example, will set up different HTTP headers to indicate a custom scheme, port, host and prefix:
> 
> x_for – Number of values to trust for X-Forwarded-For.
> x_proto – Number of values to trust for X-Forwarded-Proto.
> x_host – Number of values to trust for X-Forwarded-Host.
> x_port – Number of values to trust for X-Forwarded-Port.
> x_prefix – Number of values to trust for X-Forwarded-Prefix.
> 
> see https://werkzeug.palletsprojects.com/en/1.0.x/

This totally works.
Thank you very much.

Closing issue

**Comment by fcollman** [comment]
I might be wrong here, but the solution you provided assumes the user is running Traefik and can paste in your python code into their middleware.  this doesn't seem to be a general solution to the problem.   If i'm wrong could you explain?

**Comment by fcollman** [comment]
I see indeed I am wrong! This code above is for the flask app and you are saying the middle layer needs some header reconfiguration which will vary by what you are using.

**Comment by alexlopezc** [comment]
The solution from @mikaelmeulle works as expected without having to mess with env variables for your domain. The code I posted was just a workaround so I recommend following his code.

I do not know if the ProxyFix solution will work with other proxy reverse, but the solution is for how flask trust the forwarding headers, so it may apply to others as well.

**Comment by rodrigocaus** [comment]
The solution from @mikaelmeulle worked for kubernetes nginx.ingress target rewritting (such as /doc to /). It was only necessary to configure the nginx x-forwarded-prefix to "/doc".

**Comment by franchyze923** [comment]
I'm running into this same problem on an nginx reverse proxy setup. Here is what my proxy config looks like - 

```
        location /flaskapp/ {
               # proxy_set_header X-Forwarded-Host $host:$server_port;
               # proxy_set_header X-Forwarded-Server $host;
               # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               # proxy_pass http://192.168.0.142:1338;
                proxy_pass http://192.168.0.142:1338/;
        }
```
I'm expecting to be able to browse to /flaskapp/ and see the swagger interface because that is the behavior when I'm not proxying the request.  

I've added this line - 

`app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_port=1, x_for=1, x_host=1, x_prefix=1)`

but doesnt seem to have any effect. I also don't fully understand what it's doing. I'm serving my flask app with Waitress which I don't know if that changes things.

**Comment by stharding** [comment]
I was struggling with this same issue. The initial comment by @alexlopezc got me 99% there, but it was missing one crucial thing: relative paths.

```python
    # rewrite template urls to use relative paths to work with reverse proxy
    @apidoc.apidoc.add_app_template_global
    def swagger_static(filename):
        return f"./swaggerui/{filename}"

    api = Api(app=app, version="3.0")

    @api.documentation
    def custom_ui():
        return render_template(
            "swagger-ui.html", title=api.title, specs_url="./swagger.json"
        )

```
This works fine with the reverse proxy [I am using](https://www.npmjs.com/package/http-proxy). No need for `ProxyFix`. The swaggerui shows up correctly and I am able to interact with the api just fine; with or without the proxy. The key here is the leading `"./"` when I proxy my app to `host:port/proxy-path` the files are loaded from the relative `/proxy-path` instead of the absolute `/` which is the default.

**Comment by CpiliotisSTLA** [comment]
Posting an alternative solution as this may help someone else.  I added in a /spec path to replace swagger.json because it's not doing what I want.  

This does what I want:
```
@api.route("/spec")
@api.hide
class spec(Resource):
    @api.doc(security=[])
    def get(self):
        apischema = copy.copy(api.__schema__)
        apischema["basePath"] = APPLICATION_ROOT + "/"
        return apischema
```

And then you can just do this with your swagger ui call:
```
@api.documentation
def custom_ui():
    return render_template(
        "swagger-ui.html",
        title=api.title,
        specs_url="{}/spec".format(APPLICATION_ROOT)
    )
```

This is what I really want is to be able to set the base_url myself from an env var or something.   Ideally I'm not setting env vars myself :-)
