### ISSUE TITLE
Push Releases from CI

### ISSUE THREAD

**Issue by SteadBytes** [python-restx/flask-restx#6]
To help avoid the [problems with releasing](https://github.com/noirbizarre/flask-restplus/issues/743#issuecomment-562824068) experienced in the Flask-RESTPlus project. We should be able to make new releases to PyPi from CI - i.e. not relying on a core team member to release 'manually' from his/her own machine. 

My *initial* proposal is that CI will push a release to PyPi when a release is tagged on GitHub. I haven't put a whole lot of thought into this as of yet so suggestions are more than welcome :smile:

**Comment by cal97g** [comment]
Yes; the tag should trigger a build and the resulting package should be pushed to pypy - it should also probably run tests before it gets to that point.

CI should be setup to run tests on PR's too. 

Which tool should we use?

**Comment by ziirish** [comment]
CI is already up and running for PRs.

I'll have a look at how to build & push releases from travis to PyPi.

**Comment by SteadBytes** [comment]
@cal97g CI is already set up to run tests for PRs 😀 It’s using Travis CI as previously with Flask-RESTPlus https://github.com/python-restx/flask-restx/issues/4

**Comment by ziirish** [comment]
Our first release has been automatically published on PyPi through travis-ci. I believe this issue is now resolved.
