### ISSUE TITLE
Long type is not correctly handled by Swagger

### ISSUE THREAD

**Issue by JulienPeloton** [python-restx/flask-restx#630]
Hello,

Long values passed to `fields.Integer` seem to be incorrectly handled by Swagger.

### **Code**

```python
from flask import Flask
from flask_restx import Api, Resource, fields

app = Flask(__name__)
api = Api(app, version='1.0', title='Bug Swagger?',)

ns = api.namespace('ns')

IDs = api.model(
    'ID', 
    {
        'long_id': fields.Integer(
            example=2890466950515015016, 
            description='Something that is really a signed 64-bit integer.'
        ),
    }
)

@ns.route('/')
class myClass(Resource):
    '''Test me'''
    @ns.expect(IDs)
    def post(self):
        '''Expose ID'''
        return api.payload

if __name__ == '__main__':
    app.run(debug=True)
```

### **Repro Steps** (if applicable)
1. execute the code above
2. follow URL, expand `ns`, then expand `post`
3. Look at the payload: the example value `2890466950515015000` is different from what we define in the script (`2890466950515015016`).

![Screenshot from 2024-12-17 14-57-35](https://github.com/user-attachments/assets/1b240fca-4c50-4334-a0f9-a5f338e35622)

### **Environment**
- Python version: 3.9.12 (checked with 3.11 as well)
- Flask version: 3.0.3 (checked with 3.1.0 as well)
- Flask-RESTX version:  1.3.0
- Other installed Flask extensions: None

**Comment by peter-doggart** [comment]
This is an issue with swagger-ui and JavaScript, so it's outside the control of flask-restx: https://github.com/swagger-api/swagger-ui/issues/2030 

It's caused by javascript only supporting integers up to 53 bits:
```javascript
console.log(parseInt("2890466950515015016"))
2890466950515015000
```

Unfortunately, if you want to pass longs the safest way is to use strings in JSON and handle the conversion as part of your input validation.

**Comment by JulienPeloton** [comment]
Thanks @peter-doggart for the rapid follow-up on this, and the pointer to the discussion.

Then it will be strings!
