### ISSUE TITLE
List Response Model

### ISSUE THREAD

**Issue by Domhnall-Liopa** [python-restx/flask-restx#65]
I want to document my response model as a list of strings like: 
```
[
    "value1", 
    "value2"
]

```
which is valid JSON.
So I want to be able to do something like: 
```
response_model = ns.model('Response', [
    fields.String()
])
```

Is there a way of doing this currently without having to use a dict object in ns.model?

**Comment by SVilgelm** [comment]
You can use `fields.List(fields.String))` as a response model:

```python

@NS.route("health")
class Health(Resource):
    @NS.response(200, "successfully fetched health details", fields.List(fields.String))
    def get(self):
        """Check the health of Job Service"""
        self.logger.info("Health check is called [GET] /health")
        return {"status": "success", "message": "Health check successful"}, 200, {}
```

**Comment by SVilgelm** [comment]
<img width="584" alt="Screen Shot 2020-02-18 at 7 32 40 AM" src="https://user-images.githubusercontent.com/523825/74740660-f1f4ba00-5220-11ea-982f-33271a842b0a.png">

**Comment by Domhnall-Liopa** [comment]
Thanks @SVilgelm. Is it possible to do `fields.List()` on another model so it would return a list of dictionaries instead of strings? e.g. 

```
[
    {
        "id": 1
    }, 
    {
        "id": 2
    }
]
```

**Comment by SVilgelm** [comment]
I think yes, `fields.List(fields.Nested(MyModel))`

**Comment by SVilgelm** [comment]
Seems, the question is answered.

**Comment by po5i** [comment]
It didn't work for me, but I use the `marshal_with` decorator instead. As [the docs says](https://flask-restx.readthedocs.io/en/latest/swagger.html#documenting-with-the-api-response-decorator):

> The @api.marshal_with() decorator automatically documents the response:
```
@api.marshal_with(model, code=201, description='Object created')
```

**Comment by andreykurilin** [comment]
@po5i Try `@api.marshal_list_with` decorator instead

**Comment by etlds** [comment]
It does not work for me. This is error that I get.
TypeError: 'List' object is not iterable

Here is my model definition.
```
MyModal = api.model(
    "MyModal", fields.List(fields.Nested(NestedModal))
)
```

**Comment by po5i** [comment]
> It does not work for me. This is error that I get.
> 
> TypeError: 'List' object is not iterable
> 
> 
> 
> Here is my model definition.
> 
> ```
> 
> MyModal = api.model(
> 
>     "MyModal", fields.List(fields.Nested(NestedModal))
> 
> )
> 
> ```

I believe your model is not well defined. It contains just a field instead of a dict. See the docs and compare

**Comment by etlds** [comment]
> > It does not work for me. This is error that I get.
> > TypeError: 'List' object is not iterable
> > Here is my model definition.
> > ```
> > 
> > MyModal = api.model(
> > 
> >     "MyModal", fields.List(fields.Nested(NestedModal))
> > 
> > )
> > ```
> 
> I believe your model is not well defined. It contains just a field instead of a dict. See the docs and compare

I know that if I do this it will work. But I do want it to just a list instead of a dict. I think a "[]" is also a valid json.
```
MyModal = api.model(

    "MyModal", { "results": fields.List(fields.Nested(NestedModal))}

)
```

**Comment by po5i** [comment]
@etlds Yes, but you need to define `MyModal` as a simple dict model, then in your endpoint's logic you can return the list and marshal as list with the decorator `@api.marshal_list_with(MyModal, code=200)` or with the function `marshal_with(MyModal, as_list=True)`

**Comment by QCTW** [comment]
I solve it my defining my model as

my_dict_model = api.model('MyDModel', {"nale": fields.List(fields.String} )
my_list_model = api.model('MyLModel', my_dict_model, **as_list=True** )
