### ISSUE TITLE
Configurations still using the prefix RESTPLUS

### ISSUE THREAD

**Issue by kelvins** [python-restx/flask-restx#8]
Some configurations are still using the prefix `RESTPLUS_`, for example:

https://github.com/python-restx/flask-restx/blob/3da9017d203d3bcfbbd1ce125689dc94994496e2/flask_restx/api.py#L219-L220

Does it make sense to change the prefix to `RESTX_` (e.g. `RESTX_MASK_HEADER`)?

**Comment by SteadBytes** [comment]
Well spotted! Yes those should be changed, good job I didn't close https://github.com/python-restx/flask-restx/issues/1 last night after merging the first renaming PR 🤣 Ill take another look today to find any remaining ones like this - thanks!

**Comment by SteadBytes** [comment]
Closed by #9
