### ISSUE TITLE
Upgrade packages in light of deprecation warnings

### ISSUE THREAD

**Issue by andreixk** [python-restx/flask-restx#83]
Currently the unit tests are always throwing the following DeprecationWarnings:

> app/lib/python3.8/site-packages/flask_restx/model.py:12
>   /private/var/www/html/api/app/lib/python3.8/site-packages/flask_restx/model.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>     from collections import OrderedDict, MutableMapping
> 
> app/lib/python3.8/site-packages/flask_restx/api.py:28
>   /private/var/www/html/api/app/lib/python3.8/site-packages/flask_restx/api.py:28: DeprecationWarning: The import 'werkzeug.cached_property' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import cached_property' instead.
>     from werkzeug import cached_property
> 
> app/lib/python3.8/site-packages/flask_restx/swagger.py:12
>   /private/var/www/html/api/app/lib/python3.8/site-packages/flask_restx/swagger.py:12: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>     from collections import OrderedDict, Hashable

It would be a good idea to upgrade them to avoid broken releases in the near future

**Comment by MeLight** [comment]
Any plans on releasing this?

**Comment by ziirish** [comment]
The [0.2.0](https://github.com/python-restx/flask-restx/releases/tag/0.2.0) is now released.

Thanks for your patience.
