### ISSUE TITLE
ERROR: flask-restx 0.1.1 has requirement werkzeug<=0.16.1, but you'll have werkzeug 1.0.0 which is incompatible.

### ISSUE THREAD

**Issue by MeLight** [python-restx/flask-restx#85]
Hi, google has released an update to chrome which breaks how cookies work in 0.16.X werkzeug. werkzeug in turn released a fix, but in 1.0.0. When installing Flask-RESTX it threw this error:
ERROR: flask-restx 0.1.1 has requirement werkzeug<=0.16.1, but you'll have werkzeug 1.0.0 which is incompatible.

How would I address this?

**Comment by MeLight** [comment]
I've found that a patch was actually implemented here: https://github.com/python-restx/flask-restx/commit/312a540d29c2ca93d4cc754bdbbf209feb3c5007
!

But for some reason it is not reflected in the version that's fetched via `pip install`

**Comment by j5awry** [comment]
closing as fix is already in source. Will chat with team to get a release out.
