### ISSUE TITLE
Timeout manually

### ISSUE THREAD

**Issue by harshthakur9030** [python-restx/flask-restx#88]
I'm working with video processing of a live stream and I want to return a response after , say 30 seconds of processing if I dont find a particular result. I tried using Signal module but that doesn't work on a web server and I don't want to use the subprocess module(not sure that would either). What do I do to break out of the method?

**Comment by harshthakur9030** [comment]
@SteadBytes @noirbizarre Any thoughts?

**Comment by ziirish** [comment]
Do you have any pseudo code to share?

I'm not sure to understand what should be returned and what should trigger the "timer"


17 mars 2020 1:49:35 AM Harsh Thakur <notifications@github.com>:

**Comment by harshthakur9030** [comment]
`@upload_ns.route('/')
class upload(Resource):
    @api.expect(image_parser,validate=True)      
    def post(self):
        args =  image_parser.parse_args()
        if args['image'] : 
            found = detect_faces(args['image'].stream) # function which is processing livestream
            if found:
                return make_response(jsonify("Msg: Person Found"),200)
            else:
                return make_response(jsonify("Msg: Person not found"),417)
        else:
            return make_response(jsonify("Msg: Upload an image"),415)`

*** 
I am processing a livestream for faces . After 60 seconds, I want to stop looking for that particular face and return a response saying that face isn't found. How would I do that? Will using celery with time limit make sense?

**Comment by SteadBytes** [comment]
Unless I've misunderstood, fhis doesn't seem like a `flask-restx`issue. Some dough pseudocode within a handler method:

```python
try:
  my_video_processing(timeout=30)
  return 200
except Timeout error:
  return 408
```

**Comment by harshthakur9030** [comment]
@SteadBytes  I was wondering if the framework provides an easier way to do this sort of task.

**Comment by SteadBytes** [comment]
@harshthakur9030 No, it doesn't, this is an application specific implementation detail IMO and not necessarily easily generalisable 🤔

That was just pseudocode, `TmeoutError` is a bit more general that network issues https://docs.python.org/3/library/exceptions.html#TimeoutError however I was implying a custom exception 👍

**Comment by harshthakur9030** [comment]
Thanks for your input. Great work with the framework , really appreciate it :)

**Comment by SteadBytes** [comment]
No worries, thank you for the positive feedback!
