### ISSUE TITLE
Convert API to serverless function

### ISSUE THREAD

**Issue by harshthakur9030** [python-restx/flask-restx#89]
Is there a way I can convert my existing flask-restplus API to a serverless function? I've tried using Zappa framework to serve it but that didn't work. I know it's possible to use plain Flask but is there a way to use Flask-restplus ?

**Comment by SVilgelm** [comment]
I think you can mix this example: https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/ with a RestX Quick Strat example: https://github.com/python-restx/flask-restx#quick-start and get what you need

**Comment by harshthakur9030** [comment]
Thanks. I seem to have found the solution with no code changes. I had to use the serverless-wsgi plugin which lets me use any extension of flask without any trouble.
