### ISSUE TITLE
Unable to access nested list property using dot(.) notation as specified in documentation.

### ISSUE THREAD

**Issue by mukeshsharma1201** [python-restx/flask-restx#91]
**Code**
```
field = fields.Raw(attribute='bar.0')
assert field.output('foo', {'bar': [42]}) == 42
```
**Repro Steps (if applicable)**
Try with the above snippet

**Expected Behavior**
Properties which are nested under list should be accessible according to https://flask-restplus.readthedocs.io/en/stable/marshalling.html#renaming-attributes
AND
https://flask-restx.readthedocs.io/en/latest/marshalling.html#renaming-attributes

**Actual Behavior**
A description of the unexpected, buggy behaviour.

**Error Messages/Stack Trace**
No error/exception thrown, but it outputs None

**Environment**
Python 3.7.2
Flask 1.1.1
Werkzeug 0.16.1
Flask-RESTPlus 0.13.0
flask-restx 0.1.1

### **Additional Context**

This is the exact issue [#783](https://github.com/noirbizarre/flask-restplus/issues/783) of [flask-restplus](https://github.com/noirbizarre/flask-restplus). Since I am experiencing the same behaviour in flask-restx and there are no previous issues mentioning this, so I am creating an exact copy of the issue here! 

**There is an [open PR](https://github.com/noirbizarre/flask-restplus/pull/784) on flask-restplus that solves the issue.** I am just beginner with python and flask-restx, but if anyone can port that solution here, it would be great!

**Comment by arajkumar** [comment]
Hey, I can port the change to this active project. Thanks !

**Comment by mukeshsharma1201** [comment]
That's awesome @arajkumar!
Thank you so much, Hope this gets merged soon! 😄

**Comment by mukeshsharma1201** [comment]
Till this gets fixed I am using functions as a workaround
```
def getItem(x):
  return x[0]

field = fields.Raw(attribute=getItem)
```

**Comment by j5awry** [comment]
I've confirmed the bug, and looking at the PR now.
